(function (L) {
  'use strict';
  const DB = L.core.DatabaseService, G = L.core.ApiGateway, B = L.ui.button, E = L.escape;
  const nav = [['home','Inicio','home'],['cliente','Cliente','shopping_cart'],['restaurante','Restaurante','restaurant'],['repartidor','Repartidor','two_wheeler'],['operaciones','Operaciones','monitoring'],['middleware','Middleware','hub'],['arquitectura','Arquitectura','account_tree']];
  let renderTimer, pending = false;
  const app = L.app = {
    context() { const current = L.core.Router.current; return current==='cliente'?{ actor:'client',customerId:'c1' }:current==='restaurante'?{ actor:'restaurant',restaurantId:L.views.restaurante.id }:current==='repartidor'?{ actor:'driver',driverId:L.views.repartidor.id }:{ actor:'admin' }; },
    async api(method,url,data,context) { return (await G.request(method,url,data,context || this.context())).data; },
    render(force = false) {
      clearTimeout(renderTimer); renderTimer = null;
      if (document.getElementById('modal').open) { pending = true; return; }
      const focus = document.activeElement; if (focus && ['INPUT','TEXTAREA','SELECT'].includes(focus.tagName) && document.getElementById('view').contains(focus)) { if (!force) { pending = true; return; } focus.blur(); }
      clearTimeout(renderTimer); pending = false; L.maps.MapManager.destroy(); L.ui.charts.destroy(); const current = L.core.Router.current, view = L.views[current];
      document.getElementById('page-title').textContent = view.title; document.getElementById('page-subtitle').textContent = view.subtitle; document.getElementById('breadcrumb-view').textContent = current==='home'?'Inicio':view.title;
      const actor = this.context().actor; document.getElementById('actor-label').textContent = ({ client:'TU ESPACIO · CLIENTE', restaurant:'TU ESPACIO · RESTAURANTE', driver:'TU ESPACIO · REPARTIDOR', admin:current==='home'?'UNA CIUDAD, MUCHAS CONEXIONES':'TU ESPACIO · ADMINISTRADOR' })[actor];
      document.getElementById('role-nav').innerHTML = nav.map(([key,title,icon],i) => (i===4?'<div class="nav-separator"></div><span class="admin-nav-label">ADMINISTRADOR</span>':'')+B('navigate',title,{view:key},icon,current===key?'active':'')).join('');
      document.getElementById('mobile-nav').innerHTML = nav.slice(1,4).map(([key,title,icon]) => B('navigate',title,{view:key},icon,current===key?'active':'' )).join('')+B('more-views','Más',{},'menu',['home','operaciones','middleware','arquitectura'].includes(current)?'active':'');
      document.querySelectorAll('[data-action=navigate]').forEach(b => { if (b.dataset.view===current) b.setAttribute('aria-current','page'); });
      document.getElementById('view').innerHTML = view.render(); view.mount(); this.chrome();
    },
    chrome() { const unavailable = DB.state.unavailable; document.getElementById('service-status').innerHTML = '<span class="status-dot"></span>'+(unavailable.length?'Servicios con incidencias':'Servicios operativos'); document.getElementById('sidebar-status').innerHTML = '<span class="status-dot"></span>'+(DB.persistent?'Guardado en este navegador':'Sesión en memoria'); const count = DB.getNotifications().filter(n => !n.read && n.customerId==='c1').length; document.getElementById('notification-count').textContent = count; document.getElementById('header-bell').innerHTML = L.ui.icon('notifications'); const warning = document.getElementById('storage-warning'); warning.hidden = DB.persistent; warning.textContent = DB.warning || ''; },
    schedule(delay = 120) { if (!renderTimer) renderTimer = setTimeout(() => this.render(),delay); },
    async checkout(event) { event.preventDefault(); const form = event.target, data = Object.fromEntries(new FormData(form)), button = form.querySelector('[type=submit]'); button.disabled = true; const cart = L.copy(DB.state.cart); try { const o = await this.api('POST','/api/orders',{ ...data, items:cart, restaurantId:cart[0].restaurantId, lat:DB.state.customer.lat,lng:DB.state.customer.lng }); DB.change(s => { s.customer.name = data.customerName; s.customer.address = data.address; if (o.status!=='PAYMENT_REJECTED') s.cart = []; }); L.views.cliente.selectedOrder = o.id; L.views.cliente.tab = 'Pedido'; form.querySelector('input').blur(); this.render(); L.ui.toast(o.status==='PAYMENT_REJECTED'?'Pago rechazado. Tu carrito se conserva.':'Pedido '+o.id+' confirmado',o.status==='PAYMENT_REJECTED'); } catch (error) { document.getElementById('checkout-error').textContent = error.message; L.ui.toast(error.message,true); } finally { if (button.isConnected) button.disabled = false; } },
    location() { const c = DB.state.customer; const content = '<p class="muted">Selecciona un punto en el mapa o una zona. La dirección escrita y el punto son parte de tu entrega.</p><label>Dirección<input name="address" value="'+E(c.address)+'" required maxlength="200"></label><label>Zona<select id="location-zone"><option value="">Selecciona una zona</option>'+DB.state.zones.map(z => '<option>'+z.name+'</option>').join('')+'</select></label><div id="location-map" class="map"></div><div class="actions">'+B('geolocation','Usar mi ubicación',{},'location_on')+B('default-location','Usar ubicación predeterminada',{},'refresh')+'</div><div class="two-columns"><label>Latitud<input name="lat" value="'+c.lat+'" type="number" step="any" required></label><label>Longitud<input name="lng" value="'+c.lng+'" type="number" step="any" required></label></div><p id="location-help" class="muted">Precisión: '+(c.accuracy?c.accuracy.toFixed(0)+' m':'punto elegido')+'</p>';
      L.ui.modal('Tu ubicación en Cochabamba',content,data => { const lat = Number(data.lat),lng = Number(data.lng); if (!data.address.trim() || lat < -17.45 || lat > -17.33 || lng < -66.23 || lng > -66.09 || !Number.isFinite(lat) || !Number.isFinite(lng)) L.fail('Selecciona una dirección y un punto dentro de Cochabamba',422); DB.change(s => Object.assign(s.customer,{address:data.address.trim(),lat,lng})); if (L.views.cliente.draft) L.views.cliente.draft.address=data.address.trim(); pending = true; });
      this.mountLocationMap(c.lat,c.lng); document.getElementById('location-zone').onchange = event => { const z = DB.state.zones.find(z => z.name===event.target.value); if (z) this.setLocationFields(z.lat,z.lng); };
    },
    mountLocationMap(lat,lng) { L.maps.MapManager.mount('location-map',{ markers:[{lat,lng,name:'Tu ubicación',customer:true}],center:[lat,lng],onSelect:(a,b) => this.setLocationFields(a,b) }); },
    setLocationFields(lat,lng) { const f = document.getElementById('modal-form'); if (!f) return; f.elements.lat.value = lat.toFixed(6); f.elements.lng.value = lng.toFixed(6); document.getElementById('location-help').textContent = 'Ubicación seleccionada: '+lat.toFixed(5)+', '+lng.toFixed(5); this.mountLocationMap(lat,lng); },
    async action(button) {
      const d = button.dataset, action = d.action;
      if (action==='navigate') { L.core.Router.navigate(d.view); if (d.view==='cliente') await this.api('GET','/api/restaurants'); if (d.view==='restaurante') await this.api('GET','/api/orders'); if (d.view==='repartidor') await this.api('GET','/api/drivers'); return; }
      if (action==='client-tab') { L.views.cliente.tab = d.tab; if (d.tab==='Restaurantes' || d.tab==='Inicio' || d.tab==='Buscar') L.views.cliente.restaurantId = null; this.render(); return; }
      if (action==='restaurant-tab') { L.views.restaurante.tab = d.tab; this.render(); return; }
      if (action==='category') { L.views.cliente.category = d.category; this.render(); return; }
      if (action==='restaurant-menu') { await this.api('GET','/api/restaurants/'+d.id+'/menu'); L.views.cliente.restaurantId = d.id; L.views.cliente.tab = 'Restaurantes'; this.render(); return; }
      if (action==='back-catalog') { L.views.cliente.restaurantId = null; L.views.cliente.tab = 'Restaurantes'; L.views.cliente.search=''; L.views.cliente.category='Todas'; this.render(); return; }
      if (action==='add-cart') { const p = DB.state.products.find(p => p.id===d.id), quantity = Number(document.getElementById('qty-'+p.id).value); if (!Number.isInteger(quantity) || quantity<1 || quantity>50) L.fail('Elige entre 1 y 50 unidades',422); const add = () => { DB.change(s => { const existing = s.cart.find(i => i.productId===p.id); if (existing) { if (existing.quantity+quantity>50) L.fail('Máximo 50 unidades por producto',422); existing.quantity+=quantity; } else s.cart.push({ productId:p.id,quantity,restaurantId:p.restaurantId }); }); L.ui.toast('Agregado a tu carrito'); this.render(); }; if (DB.state.cart.length && DB.state.cart[0].restaurantId!==p.restaurantId) L.ui.confirm('Cambiar de restaurante','El carrito contiene productos de otro restaurante. Reemplazarlos por tu nueva selección.',() => { DB.change(s => { s.cart=[]; }); add(); }); else add(); return; }
      if (action==='cart-quantity') DB.change(s => { const i = s.cart.find(i => i.productId===d.id); i.quantity = Math.min(50,i.quantity+Number(d.delta)); s.cart = s.cart.filter(i => i.quantity>0); });
      if (action==='cart-remove') DB.change(s => { s.cart = s.cart.filter(i => i.productId!==d.id); });
      if (action==='location') { const checkout = document.getElementById('checkout-form'); if (checkout) L.views.cliente.draft = Object.fromEntries(new FormData(checkout)); this.location(); return; }
      if (action==='geolocation') { if (!navigator.geolocation) { document.getElementById('location-help').textContent = 'No fue posible obtener la ubicación automáticamente. Puedes seleccionar tu ubicación en el mapa.'; return; } button.disabled = true; navigator.geolocation.getCurrentPosition(position => { button.disabled=false; if (!document.getElementById('modal').open) return; this.setLocationFields(position.coords.latitude,position.coords.longitude); DB.change(s => { s.customer.accuracy = position.coords.accuracy; }); document.getElementById('location-help').textContent += ' · Precisión '+Math.round(position.coords.accuracy)+' m'; },() => { button.disabled=false; if (document.getElementById('location-help')) document.getElementById('location-help').textContent = 'No fue posible obtener la ubicación automáticamente. Puedes seleccionar tu ubicación en el mapa.'; },{ timeout:7000,maximumAge:60000 }); return; }
      if (action==='default-location') { this.setLocationFields(-17.378,-66.151); return; }
      if (action==='select-order') { await this.api('GET','/api/orders/'+d.id); L.views.cliente.selectedOrder=d.id; L.views.cliente.tab='Pedido'; }
      if (action==='receipt') { const p = await this.api('GET','/api/orders/'+d.id+'/receipt'),o=DB.getOrder(d.id); L.ui.download('comprobante-'+o.id+'.txt','LLAJTAVOY\nComprobante local · Sin cobro real\nPedido '+o.id+'\n'+o.restaurantName+'\n'+o.items.map(i => i.quantity+' × '+i.name+' = '+L.money(i.quantity*i.price)).join('\n')+'\nDelivery: '+L.money(o.delivery)+'\nTotal: '+L.money(o.total)+'\nMétodo: '+o.paymentMethod+'\nEstado pago: '+(p?.status || 'Sin pago')+'\n'+o.correlationId,'text/plain'); return; }
      if (action==='open-notifications') { L.views.cliente.tab='Notificaciones'; L.core.Router.navigate('cliente'); return; }
      if (action==='read-notification') { const n = DB.getNotifications().find(n => n.id===d.id); if (n.customerId!=='c1') L.fail('Notificación de otro cliente',403); L.services.NotificationService.read(d.id,!n.read); }
      if (action==='order-status') await this.api('PATCH','/api/orders/'+d.id+'/status',{status:d.status});
      if (action==='cancel-order' || action==='fail-delivery') { L.ui.confirm(action==='cancel-order'?'Cancelar pedido':'Reportar entrega fallida','El estado y el pago de este pedido se actualizarán en todas las vistas.',async () => { await this.api('PATCH','/api/orders/'+d.id+'/status',{status:action==='cancel-order'?'CANCELLED':'DELIVERY_FAILED'}); pending=true; }); return; }
      if (action==='restaurant-open') await this.api('PATCH','/api/restaurants/'+d.id,{open:d.open==='true'});
      if (action==='toggle-product') await this.api('PATCH','/api/products/'+d.id,{available:d.available==='true'});
      if (action==='edit-price') { const p = DB.state.products.find(p => p.id===d.id); L.ui.modal('Precio · '+p.name,'<label>Precio en bolivianos<input name="price" value="'+p.price+'" type="number" min="0.01" step="0.01" required></label>',async data => { await this.api('PATCH','/api/products/'+p.id,{price:Number(data.price)}); pending=true; }); return; }
      if (action==='new-product') { L.ui.modal('Agregar producto','<label>Nombre<input name="name" required maxlength="100"></label><label>Descripción<textarea name="description" maxlength="300"></textarea></label><label>Categoría<input name="category" value="Platos" required></label><label>Precio Bs<input name="price" type="number" min="0.01" step="0.01" required></label>',async data => { await this.api('POST','/api/products',data); pending=true; }); return; }
      if (action==='driver-availability') await this.api('PATCH','/api/drivers/'+L.views.repartidor.id,{available:d.available==='true'});
      if (action==='accept-offer' || action==='reject-offer') await this.api('POST','/api/offers/'+d.id+'/'+(action==='accept-offer'?'accept':'reject'));
      if (action==='start-route') await this.api('POST','/api/tracking/'+d.id,{leg:d.leg});
      if (action==='pause-route') await this.api('PATCH','/api/tracking/'+d.id);
      if (action==='inspect-order') { const o = await this.api('GET','/api/orders/'+d.id); L.ui.modal('Pedido '+o.id,L.ui.orderCard(o)+L.ui.timeline(o)+'<pre>'+E(JSON.stringify(o,null,2))+'</pre>',null,'Cerrar'); return; }
      if (action==='event-payload') { const e = L.core.EventStore.get(d.id); const messages = DB.state.messages.filter(m => m.eventId===e.eventId); L.ui.modal(e.routingKey,'<pre>'+E(JSON.stringify({event:e,deliveries:messages},null,2))+'</pre>',null,'Cerrar'); return; }
      if (action==='architecture-component') { L.views.arquitectura.selected=d.name; this.render(); return; }
      if (action==='scenario') { await this.api('POST','/api/admin/scenario',{action:d.key}); L.ui.toast(['NACK','RETRY','DLQ'].includes(d.key)?'Mensaje enviado a auditoría':'Escenario activado para la próxima operación'); }
      if (action==='service-offline' || action==='service-restore') { const service = document.getElementById('scenario-service').value; await this.api('POST','/api/admin/scenario',{action:action==='service-offline'?'offline':'restore',service}); L.ui.toast(service+(action==='service-offline'?' desactivado':' restaurado')); }
      if (action==='reprocess') { await this.api('POST','/api/admin/dlq/'+d.id); L.ui.toast('Mensaje reprocesado'); }
      if (action==='burst') { button.disabled=true; let rejected=0; const context={actor:'admin'}; for (let i=0;i<65;i++) { try { await G.request('GET','/api/restaurants',{},context); } catch (error) { if (error.status===429) rejected++; else throw error; } } L.ui.toast('65 requests registrados · '+rejected+' bloqueados con 429'); }
      if (action==='new-restaurant') { L.ui.modal('Alta de restaurante','<label>Nombre comercial<input name="name" required maxlength="100"></label><label>Dirección<input name="address" required maxlength="200"></label><label>Zona<select name="zone">'+DB.state.zones.map(z => '<option>'+z.name+'</option>').join('')+'</select></label><label>Categoría<input name="category" value="Comida boliviana" required></label>',async data => { await this.api('POST','/api/admin/restaurants',data); pending=true; }); return; }
      if (action==='new-driver') { L.ui.modal('Alta de repartidor','<label>Nombre<input name="name" required maxlength="80"></label><label>Vehículo<input name="vehicle" required maxlength="80"></label>',async data => { await this.api('POST','/api/admin/drivers',data); pending=true; }); return; }
      if (action==='incident') { L.ui.modal('Registrar incidente','<label>Pedido asociado<select name="orderId"><option value="">Incidente general</option>'+DB.getOrders().map(o => '<option>'+o.id+'</option>').join('')+'</select></label><label>Descripción<textarea name="note" required maxlength="500"></textarea></label>',async data => { await this.api('POST','/api/admin/incident',data); pending=true; }); return; }
      if (action==='export') { L.ui.download('llajtavoy-respaldo.json',JSON.stringify(DB.state,null,2)); return; }
      if (action==='map-mode') DB.change(s => { s.mapMode=s.mapMode==='offline'?'auto':'offline'; });
      if (action==='reset') { L.ui.confirm('Restablecer escenario','Se eliminarán los pedidos, pagos, eventos y notificaciones. Los repartidores volverán a su estado inicial y se conservará el catálogo. Puedes exportar un respaldo antes.',async () => { await this.api('POST','/api/admin/reset'); L.views.cliente.selectedOrder=null; L.views.cliente.tab='Inicio'; L.views.repartidor.id='d1'; pending=true; }); return; }
      if (action==='more-views') { L.ui.modal('Todas las vistas','<div class="actions">'+nav.map(([view,title,icon]) => B('modal-navigate',title,{view},icon)).join('')+'</div>',null,'Cerrar'); return; }
      if (action==='modal-navigate') { document.getElementById('modal').close(); L.core.Router.navigate(d.view); return; }
      this.render();
    },
    init() {
      DB.init(); const broker=L.core.EventBroker;
      broker.subscribe('q.restaurant.orders',['order.created'],'RestaurantService',e => L.services.RestaurantService.receive(e));
      broker.subscribe('q.dispatch.orders',['order.ready'],'DispatchService',e => L.services.DispatchService.search(e));
      broker.subscribe('q.driver.offers',['driver.offer.created'],'DriverService',e => L.services.DriverService.consumeOffer(e));
      broker.subscribe('q.notifications',L.services.NotificationService.patterns,'NotificationService',e => L.services.NotificationService.consume(e));
      broker.subscribe('q.analytics',['#'],'AnalyticsService',e => L.services.AnalyticsService.consume(e));
      broker.subscribe('q.audit',['#'],'AuditService',e => L.services.AuditService.consume(e));
      broker.subscribe('q.payments',['payment.*'],'PaymentService',e => L.services.PaymentService.consume(e));
      G.init(); L.core.Router.init(); document.getElementById('date-label').textContent = new Date().toLocaleDateString('es-BO',{ weekday:'long',day:'numeric',month:'long',timeZone:'America/La_Paz' });
      document.addEventListener('click',async event => { const button=event.target.closest('button[data-action]'); if (!button || button.disabled) return; try { await this.action(button); } catch (error) { L.ui.toast(error.message,true); } });
      const preserveCheckout = event => { const form=event.target.closest('#checkout-form'); if (form) L.views.cliente.draft=Object.fromEntries(new FormData(form)); };
      document.addEventListener('input',preserveCheckout);
      document.addEventListener('change',event => { preserveCheckout(event); const el=event.target; if (el.id==='restaurant-selector') L.views.restaurante.id=el.value; else if (el.id==='driver-selector') L.views.repartidor.id=el.value; else if (el.id==='customer-order') L.views.cliente.selectedOrder=el.value; else return; el.blur(); this.render(); });
      document.getElementById('modal').addEventListener('close',() => { if (pending) this.schedule(10); });
      document.addEventListener('focusout',() => { if (pending) this.schedule(100); });
      L.EventBus.on('data:changed',() => { this.chrome(); const v=L.core.Router.current; if (v==='middleware' || v==='home' || (v==='cliente' && L.views.cliente.tab==='Notificaciones')) this.schedule(v==='middleware'?900:500); });
      for (const name of ['order:updated','driver:updated','tracking:arrived','system:reset','library:ready']) L.EventBus.on(name,() => this.schedule());
      this.render(); broker.resume(); L.services.TrackingService.resume();
      window.addEventListener('pagehide',() => DB.flush());
    }
  };
  app.init();
})(window.LlajtaVoy);
