(function (L) {
  'use strict';
  const maps=new Map(),viewports=new Map(),C=L.maps.Cochabamba,E=L.escape;
  const major=new Set(['trunk','primary','secondary','tertiary','trunk_link','primary_link','secondary_link','tertiary_link']);
  function controls(entry) {
    const box=document.createElement('div'); box.className='map-tools';
    const button=(label,text,handler) => { const b=document.createElement('button'); b.type='button'; b.title=label; b.setAttribute('aria-label',label); b.textContent=text; b.onclick=e => { e.stopPropagation(); handler(b); }; box.appendChild(b); return b; };
    button('Mostrar toda la ruta y sus puntos','Ver todo',() => { entry.follow=false; entry.followButton?.setAttribute('aria-pressed','false'); entry.fit(); });
    if (entry.config.orderId) entry.followButton=button('Activar o desactivar seguimiento del repartidor','Seguir',b => { entry.follow=!entry.follow; b.setAttribute('aria-pressed',String(entry.follow)); if (entry.follow) entry.centerDriver(); });
    entry.followButton?.setAttribute('aria-pressed',String(entry.follow));
    entry.expandButton=button('Ampliar o cerrar el mapa','Ampliar',b => { const expanded=entry.el.classList.toggle('map-expanded'); b.textContent=expanded?'Cerrar':'Ampliar'; b.setAttribute('aria-pressed',String(expanded)); entry.resize(); });
    if (entry.saved?.expanded) { entry.el.classList.add('map-expanded'); entry.expandButton.textContent='Cerrar'; entry.expandButton.setAttribute('aria-pressed','true'); entry.resize(); }
    entry.el.appendChild(box); if (window.L && entry.map) { window.L.DomEvent.disableClickPropagation(box); window.L.DomEvent.disableScrollPropagation(box); }
    const hint=document.createElement('div'); hint.className='map-hint'; hint.textContent=entry.config.onSelect?'Arrastra · Amplía · Haz clic para elegir destino':'Arrastra · Rueda / pellizco para ampliar'; entry.el.appendChild(hint);
    entry.el.onkeydown=e => { if (e.key==='Escape' && entry.el.classList.contains('map-expanded')) { e.preventDefault(); e.stopPropagation(); entry.el.classList.remove('map-expanded'); entry.expandButton.textContent='Ampliar'; entry.expandButton.setAttribute('aria-pressed','false'); entry.resize(); } };
  }
  function style(f) { const t=f.tags; if (t.waterway) return {color:'#95BBCB',weight:t.waterway==='river'?7:3}; if (!t.highway) return {color:t.natural==='water'?'#A6C9D6':'#C2D2B3',weight:1,fillColor:t.natural==='water'?'#C4DFE7':'#DCE7CF',fillOpacity:.85}; const main=major.has(t.highway),walk=['footway','cycleway','path','pedestrian','steps'].includes(t.highway); return {color:walk?'#B5B8A1':main?'#D0B69A':'#D5D2CA',weight:main?7:walk?1.5:3,dashArray:walk?'3 4':undefined,opacity:1}; }
  function leaflet(entry) {
    const F=window.L,el=entry.el,config=entry.config,b=L.maps.StreetData.bounds;
    el.innerHTML=''; const map=entry.map=F.map(el,{preferCanvas:true,scrollWheelZoom:true,keyboard:true,touchZoom:true,dragging:true,zoomControl:true,minZoom:12,maxZoom:19,maxBounds:[[b.south-.008,b.west-.008],[b.north+.008,b.east+.008]],maxBoundsViscosity:.8}).setView(config.center || C.center,config.onSelect?16:14);
    const streets=L.maps.StreetData.features.filter(f => f.tags.highway).sort((a,b) => Number(major.has(b.tags.highway))-Number(major.has(a.tags.highway))),roadLayers=[],labels=F.layerGroup().addTo(map);
    map.attributionControl.addAttribution('<a href="https://www.openstreetmap.org/copyright" target="_blank" rel="noopener">© OpenStreetMap contributors</a> · Calles locales');
    F.control.scale({imperial:false,maxWidth:90}).addTo(map);
    for (const f of L.maps.StreetData.features.filter(f => !f.tags.highway)) { const closed=f.points[0][0]===f.points.at(-1)[0] && f.points[0][1]===f.points.at(-1)[1]; (closed?F.polygon(f.points,style(f)):F.polyline(f.points,style(f))).addTo(map); }
    const groups=new Map(); for (const f of streets) { const key=f.tags.highway; if (!groups.has(key)) groups.set(key,[]); groups.get(key).push(f); }
    for (const [type,features] of groups) { const layer=F.polyline(features.map(f => f.points),{...style(features[0]),interactive:false}).addTo(map); roadLayers.push({type,layer}); }
    F.rectangle([[b.south,b.west],[b.north,b.east]],{color:'#857A9F',weight:1,dashArray:'5 8',fill:false,interactive:false}).addTo(map);
    const labelRoads=() => { labels.clearLayers(); const cells=new Set(),names=new Set(),size=map.getSize(),zoom=map.getZoom(); for (const {type,layer} of roadLayers) { const main=major.has(type),walk=['footway','path','steps'].includes(type); layer.setStyle({opacity:walk && zoom<15?0:1,weight:main?(zoom>=16?10:7):zoom>=16?5:3}); } for (const f of streets) { const main=major.has(f.tags.highway); if (!f.tags.name || (!main && zoom<16) || names.has(f.tags.name)) continue; const p=f.points[Math.floor(f.points.length/2)],xy=map.latLngToContainerPoint(p); if (xy.x<35 || xy.y<60 || xy.x>size.x-35 || xy.y>size.y-35) continue; const cell=Math.floor(xy.x/135)+','+Math.floor(xy.y/35); if (cells.has(cell)) continue; names.add(f.tags.name); cells.add(cell); F.marker(p,{interactive:false,keyboard:false,icon:F.divIcon({className:'street-label',html:E(f.tags.name.replace(/\bAvenida\b/g,'Av.').replace(/\bGeneral\b/g,'Gral.').replace(/\bCoronel\b/g,'Cnl.')),iconSize:[150,20],iconAnchor:[75,10]})}).addTo(labels); } };
    let labelTimer; map.on('moveend zoomend',() => { if (!labelTimer) labelTimer=setTimeout(() => { labelTimer=null; labelRoads(); },120); viewports.set(entry.key,{center:map.getCenter(),zoom:map.getZoom(),follow:entry.follow,expanded:entry.el.classList.contains('map-expanded')}); }); entry.cleanup=() => clearTimeout(labelTimer);
    map.on('dragstart',() => { entry.interacting=true; entry.follow=false; entry.followButton?.setAttribute('aria-pressed','false'); }); map.on('zoomstart',() => { entry.interacting=true; });
    const idle=() => { entry.interacting=false; L.EventBus.emit('map:idle'); }; map.on('dragend',idle); map.on('zoomend',idle);
    for (const m of config.markers) { const marker=F.marker([m.lat,m.lng],{draggable:!!(m.customer && config.onSelect),icon:F.divIcon({className:'pin '+(m.driver?'driver':m.customer?'customer':''),html:L.ui.icon(m.driver?'two_wheeler':m.customer?'location_on':'restaurant'),iconSize:[32,32],iconAnchor:[16,16]})}).addTo(map).bindTooltip(E(m.name)); if (m.driver) entry.driverMarkers.set(m.id,marker); if (m.customer) { entry.customerMarker=marker; if (config.onSelect) marker.on('dragend',() => { const p=marker.getLatLng(); config.onSelect(p.lat,p.lng); }); } }
    if (config.route?.length) { F.polyline(config.route,{color:'white',weight:9,interactive:false}).addTo(map); for (const s of config.plan?.segments || [{type:'street',points:config.route}]) F.polyline(s.points,{color:s.type==='access'?'#916052':'#326779',weight:5,dashArray:s.type==='access'?'4 6':undefined,interactive:false}).addTo(map); }
    const points=[...(config.route || []),...config.markers.map(m => [m.lat,m.lng])];
    entry.fit=() => { if (points.length>1) map.fitBounds(F.latLngBounds(points),{padding:[42,50],maxZoom:16,animate:false}); else map.setView(config.center || points[0] || C.center,16); };
    entry.centerDriver=() => { const t=config.orderId && L.core.DatabaseService.getOrder(config.orderId)?.tracking; if (t) map.panTo(t.position,{animate:false}); };
    entry.resize=() => map.invalidateSize({pan:false});
    const saved=entry.saved; if (saved?.center) { map.setView(saved.center,saved.zoom); entry.follow=saved.follow; } else if (!config.onSelect) entry.fit();
    if (config.onSelect) map.on('click',e => config.onSelect(e.latlng.lat,e.latlng.lng)); controls(entry); labelRoads();
    if (window.ResizeObserver) { entry.observer=new ResizeObserver(entry.resize); entry.observer.observe(el); }
  }
  function fallback(entry) {
    const el=entry.el,b=L.maps.StreetData.bounds,w=1000,h=(b.north-b.south)/(b.east-b.west)*1000/Math.cos(C.center[0]*Math.PI/180);
    const project=p => [(p[1]-b.west)/(b.east-b.west)*w,(b.north-p[0])/(b.north-b.south)*h],path=points => points.map(project).map(p => p.join(',')).join(' ');
    let v={x:0,y:0,w,h},drag; el.innerHTML='<svg class="vector-fallback" role="application" tabindex="0" aria-label="Mapa de calles de Cochabamba. Flechas para mover; más y menos para zoom."><rect x="-10000" y="-10000" width="20000" height="20000" fill="#F1F0E9"/>'+L.maps.StreetData.features.map(f => '<polyline points="'+path(f.points)+'" fill="none" stroke="'+style(f).color+'" stroke-width="'+(major.has(f.tags.highway)?2:.7)+'"><title>'+E(f.tags.name || f.tags.highway || 'Área')+'</title></polyline>').join('')+(entry.config.route?.length?'<polyline points="'+path(entry.config.route)+'" fill="none" stroke="#326779" stroke-width="4" vector-effect="non-scaling-stroke"/>':'')+entry.config.markers.map(m => '<circle data-map-marker="'+E(m.id || (m.customer?'customer':''))+'" cx="'+project([m.lat,m.lng])[0]+'" cy="'+project([m.lat,m.lng])[1]+'" r="6" stroke="white" stroke-width="2" fill="'+(m.driver?'#65785D':m.customer?'#916052':'#C48B82')+'"><title>'+E(m.name)+'</title></circle>').join('')+'</svg><span class="map-source">© OpenStreetMap contributors · Cartografía local</span>';
    const svg=el.querySelector('svg'),draw=() => { svg.setAttribute('viewBox',[v.x,v.y,v.w,v.h].join(' ')); viewports.set(entry.key,{vector:{...v}}); };
    const xy=e => { const r=svg.getBoundingClientRect(); return [(e.clientX-r.left)/r.width,(e.clientY-r.top)/r.height]; };
    const zoom=(factor,x=.5,y=.5) => { const next=Math.max(w/100,Math.min(w*1.3,v.w*factor)),ratio=next/v.w; v.x+=v.w*x*(1-ratio); v.y+=v.h*y*(1-ratio); v.w=next; v.h*=ratio; draw(); };
    svg.setAttribute('preserveAspectRatio','none'); svg.style.touchAction='none';
    svg.onwheel=e => { e.preventDefault(); zoom(e.deltaY>0?1.2:1/1.2,...xy(e)); };
    svg.onpointerdown=e => { entry.interacting=true; entry.follow=false; entry.followButton?.setAttribute('aria-pressed','false'); drag={id:e.pointerId,x:e.clientX,y:e.clientY,v:{...v},moved:false}; svg.setPointerCapture(e.pointerId); };
    svg.onpointermove=e => { if (!drag || drag.id!==e.pointerId) return; const r=svg.getBoundingClientRect(),dx=e.clientX-drag.x,dy=e.clientY-drag.y; if (Math.hypot(dx,dy)>4) drag.moved=true; v.x=drag.v.x-dx/r.width*v.w; v.y=drag.v.y-dy/r.height*v.h; draw(); };
    svg.onpointerup=e => { if (drag && !drag.moved && entry.config.onSelect) { const p=xy(e); entry.config.onSelect(b.north-(v.y+p[1]*v.h)/h*(b.north-b.south),b.west+(v.x+p[0]*v.w)/w*(b.east-b.west)); } drag=null; entry.interacting=false; L.EventBus.emit('map:idle'); }; svg.onpointercancel=() => { drag=null; entry.interacting=false; L.EventBus.emit('map:idle'); };
    svg.onkeydown=e => { if (['+','=','-'].includes(e.key)) zoom(e.key==='-'?1.2:1/1.2); else if (e.key.startsWith('Arrow')) { if (e.key==='ArrowLeft') v.x-=v.w*.1; if (e.key==='ArrowRight') v.x+=v.w*.1; if (e.key==='ArrowUp') v.y-=v.h*.1; if (e.key==='ArrowDown') v.y+=v.h*.1; draw(); } else return; e.preventDefault(); };
    entry.fit=() => { const points=[...(entry.config.route || []),...entry.config.markers.map(m => [m.lat,m.lng])].map(project); const minX=Math.min(...points.map(p => p[0])),maxX=Math.max(...points.map(p => p[0])),minY=Math.min(...points.map(p => p[1])),maxY=Math.max(...points.map(p => p[1])); const rect=svg.getBoundingClientRect(),aspect=(rect.width || 600)/(rect.height || 320); v.w=Math.max((maxX-minX)*1.5,(maxY-minY)*aspect*1.5,100); v.h=v.w/aspect; v.x=(minX+maxX-v.w)/2; v.y=(minY+maxY-v.h)/2; draw(); };
    entry.centerDriver=() => { const t=entry.config.orderId && L.core.DatabaseService.getOrder(entry.config.orderId)?.tracking; if (t) { const p=project(t.position); v.x=p[0]-v.w/2; v.y=p[1]-v.h/2; draw(); } }; entry.resize=() => { const r=svg.getBoundingClientRect(); v.h=v.w*(r.height || 320)/(r.width || 600); draw(); }; entry.project=project;
    const saved=entry.saved; if (saved?.vector) { v=saved.vector; entry.resize(); } else entry.fit(); controls(entry);
    const tools=el.querySelector('.map-tools'); for (const [text,f] of [['+',1/1.2],['−',1.2]]) { const btn=document.createElement('button'); btn.type='button'; btn.textContent=text; btn.setAttribute('aria-label',text==='+'?'Acercar mapa':'Alejar mapa'); btn.onclick=() => zoom(f); tools.appendChild(btn); }
  }
  function remove(entry) { const saved=entry.map?{center:entry.map.getCenter(),zoom:entry.map.getZoom(),follow:entry.follow}:viewports.get(entry.key) || {}; viewports.set(entry.key,{...saved,expanded:entry.el.classList.contains('map-expanded'),focused:document.activeElement===entry.el}); entry.cleanup?.(); entry.observer?.disconnect(); entry.map?.remove(); }
  L.maps.MapManager={
    isInteracting() { return [...maps.values()].some(entry => entry.interacting); },
    destroy() { for (const entry of maps.values()) remove(entry); maps.clear(); },
    mount(id,config) { const el=document.getElementById(id); if (!el) return; const prior=maps.get(id); if (prior) remove(prior); const entry={el,config,key:config.key || id,map:null,follow:false,driverMarkers:new Map()}; entry.saved=viewports.get(entry.key); maps.set(id,entry); try { if (window.L) leaflet(entry); else fallback(entry); } catch (e) { entry.cleanup?.(); entry.observer?.disconnect(); entry.map?.remove(); entry.map=null; fallback(entry); } if (entry.saved?.focused) entry.el.focus?.({preventScroll:true}); if (config.error) { const warning=document.createElement('div'); warning.className='map-warning'; warning.textContent=config.error; el.appendChild(warning); } },
    selectLocation(lat,lng,recenter=false) { const entry=maps.get('location-map'); if (!entry) return; entry.customerMarker?.setLatLng([lat,lng]); if (entry.map && recenter) entry.map.panTo([lat,lng]); if (!entry.map) { const p=entry.project([lat,lng]),marker=entry.el.querySelector('[data-map-marker="customer"]'); marker?.setAttribute('cx',p[0]); marker?.setAttribute('cy',p[1]); } },
    frame(orderId,t) { const o=L.core.DatabaseService.getOrder(orderId); for (const entry of maps.values()) { if (entry.map) { entry.driverMarkers.get(o.driverId)?.setLatLng(t.position); if (entry.follow && entry.config.orderId===orderId) entry.centerDriver(); } else { const marker=entry.el.querySelector('[data-map-marker="'+o.driverId+'"]'); if (marker) { const p=entry.project(t.position); marker.setAttribute('cx',p[0]); marker.setAttribute('cy',p[1]); } if (entry.follow && entry.config.orderId===orderId) entry.centerDriver(); } } document.querySelectorAll('[data-track="'+orderId+'"]').forEach(el => { const key=el.dataset.metric; if (key==='progress') { el.style.width=t.progress*100+'%'; el.parentElement.setAttribute('aria-valuenow',Math.round(t.progress*100)); } else if (key==='street') el.textContent=L.services.TrackingService.currentStep(t)?.name || 'Llegada al destino'; else el.textContent=key==='eta'?t.eta+' min':key==='distance'?t.remainingKm.toFixed(2)+' km':Math.round(t.progress*100)+'%'; }); },
    overview() { const s=L.core.DatabaseService.state; return {markers:[...s.restaurants.map(r => ({...r})),...s.drivers.map(d => ({...d,driver:true})),...s.orders.filter(o => !L.core.StateMachine.terminal.includes(o.status)).map(o => ({id:o.id,lat:o.lat,lng:o.lng,name:o.id,customer:true}))]}; },
    order(o) { const r=L.services.CatalogService.restaurant(o.restaurantId),d=o.driverId?L.services.DriverService.get(o.driverId):null; const markers=[{...r},{lat:o.lat,lng:o.lng,name:o.customerName,customer:true}]; if (d) markers.push({...d,driver:true,lat:o.tracking?.position[0] ?? d.lat,lng:o.tracking?.position[1] ?? d.lng}); let plan=o.tracking?.routePlan,error; if (!plan) try { plan=L.maps.Routes.plan([r.lat,r.lng],[o.lat,o.lng],L.maps.StreetNetwork.profile(d?.vehicle)); } catch (e) { error=e.message; } return {key:'order-'+o.id+'-'+(o.tracking?.leg || 'reference'),orderId:o.id,markers,plan,route:plan?.points,error}; }
  };
  L.EventBus.on('tracking:frame',e => L.maps.MapManager.frame(e.orderId,e.tracking));
})(window.LlajtaVoy);
