(function (L) {
  'use strict';
  const maps=new Map(),viewports=new Map(),C=L.maps.Cochabamba,E=L.escape;
  const major=new Set(['trunk','primary','secondary','tertiary','trunk_link','primary_link','secondary_link','tertiary_link']);
  function fleetHUD(entry){if(entry.config.fleet){const config=entry.config,el=entry.el,F=window.L;const hud=document.createElement('div');hud.className='fleet-map-hud';hud.innerHTML='<strong>Flota · Demostración</strong><small>Borde discontinuo: territorio cartográfico disponible.</small><p>'+config.markers.filter(m=>m.driver && m.status==='AVAILABLE').length+' libres · '+(config.routes || []).length+' rutas asignadas</p><small>Pasa el cursor o toca un pin para ver estado, destino y contactos.</small>'+((config.routes || []).length?'<div class="fleet-route-list">'+config.routes.map(trip=>L.ui.button('watch-order',E(trip.orderId)+' · '+E(trip.destination),{id:trip.orderId},'route')).join('')+'</div>':'<p>Sin rutas todavía. Crea un pedido y prepara la comida para activar el despacho.</p>'+L.ui.button('navigate','Crear un pedido',{view:'cliente'},'shopping_cart'))+((config.errors || []).length?'<p>'+E(config.errors.join(' · '))+'</p>':'');entry.hud=hud;el.appendChild(hud);if(entry.map){F.DomEvent.disableClickPropagation(hud);F.DomEvent.disableScrollPropagation(hud);}}}
  function controls(entry) {
    const box=document.createElement('div'); box.className='map-tools';
    const button=(label,text,handler) => { const b=document.createElement('button'); b.type='button'; b.title=label; b.setAttribute('aria-label',label); b.textContent=text; b.onclick=e => { e.stopPropagation(); handler(b); }; box.appendChild(b); return b; };
    button('Mostrar toda la ruta y sus puntos','Ver todo',() => { entry.follow=false; entry.followButton?.setAttribute('aria-pressed','false'); entry.fit(); });
    if(entry.config.fleet){button('Mostrar el territorio cartográfico disponible','Territorio',()=>entry.fitTerritory());const panel=button('Mostrar u ocultar información de flota','Panel',b=>{entry.hud.hidden=!entry.hud.hidden;b.setAttribute('aria-pressed',String(!entry.hud.hidden));});panel.setAttribute('aria-pressed','true');}
    if (entry.config.orderId) { entry.followButton=button('Activar o desactivar seguimiento del repartidor','Seguir repartidor',b => { entry.follow=!entry.follow; b.setAttribute('aria-pressed',String(entry.follow)); if (entry.follow) entry.centerDriver(); }); entry.followButton.disabled=!entry.config.hasPosition || entry.config.canFollow===false; }
    entry.followButton?.setAttribute('aria-pressed',String(entry.follow));
    entry.expandButton=button('Ampliar o cerrar el mapa','Ampliar',b => { const expanded=entry.el.classList.toggle('map-expanded'); b.textContent=expanded?'Cerrar':'Ampliar'; b.setAttribute('aria-pressed',String(expanded)); entry.resize();if(expanded && entry.config.fleet)entry.fitTerritory(); });
    if (entry.saved?.expanded) { entry.el.classList.add('map-expanded'); entry.expandButton.textContent='Cerrar'; entry.expandButton.setAttribute('aria-pressed','true'); entry.resize(); }
    entry.el.appendChild(box); if (window.L && entry.map) { window.L.DomEvent.disableClickPropagation(box); window.L.DomEvent.disableScrollPropagation(box); }
    const hint=document.createElement('div'); hint.className='map-hint'; hint.textContent=entry.config.onSelect?'Arrastra · Amplía · Haz clic para elegir destino':'Arrastra · Rueda / pellizco para ampliar'; entry.el.appendChild(hint);
    fleetHUD(entry);
    entry.el.onkeydown=e => { if (e.key==='Escape' && entry.el.classList.contains('map-expanded')) { e.preventDefault(); e.stopPropagation(); entry.el.classList.remove('map-expanded'); entry.expandButton.textContent='Ampliar'; entry.expandButton.setAttribute('aria-pressed','false'); entry.resize(); } };
  }
  function style(f) { const t=f.tags; if (t.waterway) return {color:'#95BBCB',weight:t.waterway==='river'?7:3}; if (!t.highway) return {color:t.natural==='water'?'#A6C9D6':'#C2D2B3',weight:1,fillColor:t.natural==='water'?'#C4DFE7':'#DCE7CF',fillOpacity:.85}; const main=major.has(t.highway),walk=['footway','cycleway','path','pedestrian','steps'].includes(t.highway); return {color:walk?'#B5B8A1':main?'#D0B69A':'#D5D2CA',weight:main?7:walk?1.5:3,dashArray:walk?'3 4':undefined,opacity:1}; }
  function leaflet(entry) {
    const F=window.L,el=entry.el,config=entry.config,b=L.maps.StreetData.bounds;
    el.innerHTML=''; const map=entry.map=F.map(el,{preferCanvas:true,scrollWheelZoom:true,keyboard:true,touchZoom:true,dragging:true,zoomControl:true,minZoom:12,maxZoom:19,maxBounds:[[b.south-.008,b.west-.008],[b.north+.008,b.east+.008]],maxBoundsViscosity:.8}).setView(config.center || C.center,config.onSelect?16:14);
    const streets=L.maps.StreetData.features.filter(f => f.tags.highway).sort((a,b) => Number(major.has(b.tags.highway))-Number(major.has(a.tags.highway))),roadLayers=[],labels=F.layerGroup().addTo(map);
    map.attributionControl.addAttribution('<a href="https://www.openstreetmap.org/copyright" target="_blank" rel="noopener">© OpenStreetMap contributors</a> · Calles locales');
    F.control.scale({imperial:false,maxWidth:90}).addTo(map);
    for (const f of L.maps.StreetData.features.filter(f => !f.tags.highway)) { const closed=f.points[0][0]===f.points.at(-1)[0] && f.points[0][1]===f.points.at(-1)[1]; (closed?F.polygon(f.points,style(f)):F.polyline(f.points,style(f))).addTo(map); }
    const groups=new Map(); for (const f of streets) { const key=f.tags.highway; if (!groups.has(key)) groups.set(key,[]); groups.get(key).push(f); }
    for (const [type,features] of groups) { const layer=F.polyline(features.map(f => f.points),{...style(features[0]),interactive:false}).addTo(map); roadLayers.push({type,layer}); }
    F.rectangle([[b.south,b.west],[b.north,b.east]],{color:'#857A9F',weight:1,dashArray:'5 8',fill:false,interactive:false}).addTo(map);
    const labelRoads=() => { labels.clearLayers(); const cells=new Set(),names=new Set(),size=map.getSize(),zoom=map.getZoom(); for (const {type,layer} of roadLayers) { const main=major.has(type),walk=['footway','path','steps'].includes(type); layer.setStyle({opacity:walk && zoom<15?0:1,weight:main?(zoom>=16?10:7):zoom>=16?5:3}); } for (const f of streets) { const main=major.has(f.tags.highway); if (!f.tags.name || (!main && zoom<16) || names.has(f.tags.name)) continue; const p=f.points[Math.floor(f.points.length/2)],xy=map.latLngToContainerPoint(p); if (xy.x<35 || xy.y<60 || xy.x>size.x-35 || xy.y>size.y-35) continue; const cell=Math.floor(xy.x/135)+','+Math.floor(xy.y/35); if (cells.has(cell)) continue; names.add(f.tags.name); cells.add(cell); F.marker(p,{interactive:false,keyboard:false,icon:F.divIcon({className:'street-label',html:E(f.tags.name.replace(/\bAvenida\b/g,'Av.').replace(/\bGeneral\b/g,'Gral.').replace(/\bCoronel\b/g,'Cnl.')),iconSize:[150,20],iconAnchor:[75,10]})}).addTo(labels); } };
    let labelTimer; map.on('moveend zoomend',() => { if (!labelTimer) labelTimer=setTimeout(() => { labelTimer=null; labelRoads(); },120); viewports.set(entry.key,{center:map.getCenter(),zoom:map.getZoom(),follow:entry.follow,expanded:entry.el.classList.contains('map-expanded')}); }); entry.cleanup=() => clearTimeout(labelTimer);
    map.on('dragstart',() => { entry.interacting=true; entry.follow=false; entry.followButton?.setAttribute('aria-pressed','false'); }); map.on('zoomstart',() => { entry.interacting=true; });
    const idle=() => { entry.interacting=false; L.EventBus.emit('map:idle'); }; map.on('dragend',idle); map.on('zoomend',idle);
    for (const m of config.markers) { const marker=F.marker([m.lat,m.lng],{draggable:!!(m.customer && config.onSelect),icon:F.divIcon({className:'pin '+(m.driver?'driver '+(({AVAILABLE:'available',OFFLINE:'offline',OFFERED:'offered'})[m.status] || 'busy'):m.customer?'customer':''),html:(m.driver?'<i class="driver-bearing" aria-hidden="true"></i>':'')+L.ui.icon(m.driver?'two_wheeler':m.customer?'location_on':'restaurant'),iconSize:[32,32],iconAnchor:[16,16]})}).addTo(map).bindTooltip(m.tooltip || E(m.name),{direction:'top',sticky:true,className:'fleet-tooltip'});if(m.popup)marker.bindPopup?.(m.popup,{maxWidth:280}); if (m.driver) entry.driverMarkers.set(m.id,marker); if (m.customer) { entry.customerMarker=marker; if (config.onSelect) marker.on('dragend',() => { const p=marker.getLatLng(); config.onSelect(p.lat,p.lng); }); } }
    if (config.route?.length) { F.polyline(config.route,{color:'white',weight:9,interactive:false}).addTo(map); for (const s of config.plan?.segments || [{type:'street',points:config.route}]) F.polyline(s.points,{color:s.type==='access'?'#916052':'#326779',weight:5,dashArray:s.type==='access'?'4 6':undefined,interactive:false}).addTo(map); }
    entry.fleetTrails=new Map();for(const trip of config.routes || []){if(trip.future)F.polyline(trip.future.points,{color:'#B18867',weight:3,dashArray:'5 8',interactive:false}).addTo(map);const line=F.polyline(trip.plan.points,{color:trip.running?'#326779':'#916052',weight:5,dashArray:trip.running?undefined:'7 6',className:trip.running?'fleet-route running':'fleet-route planned'}).addTo(map);line.bindTooltip?.(E(trip.name)+'<br>'+E(L.core.StateMachine.label(trip.status)));line.bindPopup?.('<div class="fleet-popup"><strong>'+E(trip.name)+'</strong><p>'+E(L.core.StateMachine.label(trip.status))+'</p>'+L.ui.button('watch-order','Seguir entrega',{id:trip.orderId},'route')+'</div>');const t=L.core.DatabaseService.state.orders.find(o=>o.id===trip.orderId)?.tracking;if(t)entry.fleetTrails.set(trip.orderId,F.polyline(L.maps.Routes.completed(t.points,t.progress),{color:'#537B59',weight:5,interactive:false}).addTo(map));}
    const territory=F.latLngBounds([[b.south,b.west],[b.north,b.east]]);entry.fitTerritory=()=>map.fitBounds(territory,{padding:[25,30],animate:false});
    const points=[...(config.route || []),...config.markers.map(m => [m.lat,m.lng])];
    entry.fit=() => { if (points.length>1) map.fitBounds(F.latLngBounds(points),{padding:[42,50],maxZoom:16,animate:false}); else map.setView(config.center || points[0] || C.center,16); };
    if(config.hasPosition) entry.trail=F.polyline(L.maps.Routes.completed(config.route,config.progress || 0),{color:'#537B59',weight:5,interactive:false}).addTo(map);
    entry.centerDriver=() => { const t=config.orderId && L.core.DatabaseService.getOrder(config.orderId)?.tracking; if (t) map.panTo(t.position,{animate:false}); };
    entry.resize=() => {map.invalidateSize({pan:false});if(map.getBoundsZoom && map.setMinZoom)map.setMinZoom(Math.max(12,map.getBoundsZoom(territory,false,[20,20])));};
    const saved=entry.saved; if (saved?.center) { map.setView(saved.center,saved.zoom); entry.follow=saved.follow; } else if(entry.follow && config.hasPosition) {map.setView(config.position,L.services.TrackingService.parameters.followZoom || 16); } else if (!config.onSelect) entry.fit();
    if (config.onSelect) map.on('click',e => config.onSelect(e.latlng.lat,e.latlng.lng)); controls(entry);labelRoads();
    if (window.ResizeObserver) { entry.observer=new ResizeObserver(entry.resize); entry.observer.observe(el); }
  }
  function fallback(entry) {
    const el=entry.el,b=L.maps.StreetData.bounds,w=1000,h=(b.north-b.south)/(b.east-b.west)*1000/Math.cos(C.center[0]*Math.PI/180);
    const project=p => [(p[1]-b.west)/(b.east-b.west)*w,(b.north-p[0])/(b.north-b.south)*h],path=points => points.map(project).map(p => p.join(',')).join(' ');
    let v={x:0,y:0,w,h},drag; el.innerHTML='<svg class="vector-fallback" role="application" tabindex="0" aria-label="Mapa de calles de Cochabamba. Flechas para mover; más y menos para zoom."><rect x="-10000" y="-10000" width="20000" height="20000" fill="#F1F0E9"/>'+L.maps.StreetData.features.map(f => '<polyline points="'+path(f.points)+'" fill="none" stroke="'+style(f).color+'" stroke-width="'+(major.has(f.tags.highway)?2:.7)+'"><title>'+E(f.tags.name || f.tags.highway || 'Área')+'</title></polyline>').join('')+(entry.config.route?.length?'<polyline points="'+path(entry.config.route)+'" fill="none" stroke="#326779" stroke-width="4" vector-effect="non-scaling-stroke"/>':'')+entry.config.markers.map(m => '<circle data-map-marker="'+E(m.id || (m.customer?'customer':''))+'" cx="'+project([m.lat,m.lng])[0]+'" cy="'+project([m.lat,m.lng])[1]+'" r="6" stroke="white" stroke-width="2" fill="'+(m.driver?'#65785D':m.customer?'#916052':'#C48B82')+'"><title>'+E(m.name)+'</title></circle>').join('')+'</svg><span class="map-source">© OpenStreetMap contributors · Cartografía local</span>';
    const svg=el.querySelector('svg'),draw=() => { svg.setAttribute('viewBox',[v.x,v.y,v.w,v.h].join(' ')); viewports.set(entry.key,{vector:{...v},follow:entry.follow}); };
    if(entry.config.hasPosition) { const trail=document.createElementNS('http://www.w3.org/2000/svg','polyline');trail.setAttribute('fill','none');trail.setAttribute('stroke','#537B59');trail.setAttribute('stroke-width','4');trail.setAttribute('vector-effect','non-scaling-stroke');svg.appendChild(trail);entry.updateTrail=points=>trail.setAttribute('points',path(points));entry.updateTrail(L.maps.Routes.completed(entry.config.route,entry.config.progress || 0)); }
    entry.fleetVectors=new Map();for(const trip of entry.config.routes || []){const add=(points,color,dash)=>{const line=document.createElementNS('http://www.w3.org/2000/svg','polyline');line.setAttribute('points',path(points));line.setAttribute('stroke',color);line.setAttribute('fill','none');line.setAttribute('stroke-width','4');line.setAttribute('vector-effect','non-scaling-stroke');if(dash)line.setAttribute('stroke-dasharray',dash);svg.appendChild(line);return line;};if(trip.future)add(trip.future.points,'#B18867','5 8');add(trip.plan.points,trip.running?'#326779':'#916052',trip.running?null:'7 6');const t=L.core.DatabaseService.state.orders.find(o=>o.id===trip.orderId)?.tracking;if(t)entry.fleetVectors.set(trip.orderId,add(L.maps.Routes.completed(t.points,t.progress),'#537B59'));}
    const xy=e => { const r=svg.getBoundingClientRect(); return [(e.clientX-r.left)/r.width,(e.clientY-r.top)/r.height]; };
    const zoom=(factor,x=.5,y=.5) => { const next=Math.max(w/100,Math.min(w*1.3,v.w*factor)),ratio=next/v.w; v.x+=v.w*x*(1-ratio); v.y+=v.h*y*(1-ratio); v.w=next; v.h*=ratio; draw(); };
    svg.setAttribute('preserveAspectRatio','none'); svg.style.touchAction='none';
    svg.onwheel=e => { e.preventDefault(); zoom(e.deltaY>0?1.2:1/1.2,...xy(e)); };
    svg.onpointerdown=e => { entry.interacting=true; entry.follow=false; entry.followButton?.setAttribute('aria-pressed','false'); drag={id:e.pointerId,x:e.clientX,y:e.clientY,v:{...v},moved:false}; svg.setPointerCapture(e.pointerId); };
    svg.onpointermove=e => { if (!drag || drag.id!==e.pointerId) return; const r=svg.getBoundingClientRect(),dx=e.clientX-drag.x,dy=e.clientY-drag.y; if (Math.hypot(dx,dy)>4) drag.moved=true; v.x=drag.v.x-dx/r.width*v.w; v.y=drag.v.y-dy/r.height*v.h; draw(); };
    svg.onpointerup=e => { if (drag && !drag.moved && entry.config.onSelect) { const p=xy(e); entry.config.onSelect(b.north-(v.y+p[1]*v.h)/h*(b.north-b.south),b.west+(v.x+p[0]*v.w)/w*(b.east-b.west)); } drag=null; entry.interacting=false; L.EventBus.emit('map:idle'); }; svg.onpointercancel=() => { drag=null; entry.interacting=false; L.EventBus.emit('map:idle'); };
    svg.onkeydown=e => { if (['+','=','-'].includes(e.key)) zoom(e.key==='-'?1.2:1/1.2); else if (e.key.startsWith('Arrow')) { if (e.key==='ArrowLeft') v.x-=v.w*.1; if (e.key==='ArrowRight') v.x+=v.w*.1; if (e.key==='ArrowUp') v.y-=v.h*.1; if (e.key==='ArrowDown') v.y+=v.h*.1; draw(); } else return; e.preventDefault(); };
    entry.fitTerritory=()=>{v={x:0,y:0,w,h};entry.resize();};
    entry.fit=() => { const points=[...(entry.config.route || []),...entry.config.markers.map(m => [m.lat,m.lng])].map(project); const minX=Math.min(...points.map(p => p[0])),maxX=Math.max(...points.map(p => p[0])),minY=Math.min(...points.map(p => p[1])),maxY=Math.max(...points.map(p => p[1])); const rect=svg.getBoundingClientRect(),aspect=(rect.width || 600)/(rect.height || 320); v.w=Math.max((maxX-minX)*1.5,(maxY-minY)*aspect*1.5,100); v.h=v.w/aspect; v.x=(minX+maxX-v.w)/2; v.y=(minY+maxY-v.h)/2; draw(); };
    entry.centerDriver=() => { const t=entry.config.orderId && L.core.DatabaseService.getOrder(entry.config.orderId)?.tracking; if (t) { const p=project(t.position); v.x=p[0]-v.w/2; v.y=p[1]-v.h/2; draw(); } }; entry.resize=() => { const r=svg.getBoundingClientRect(); v.h=v.w*(r.height || 320)/(r.width || 600); draw(); }; entry.project=project;
    const saved=entry.saved; if (saved?.vector) { v=saved.vector; entry.follow=saved.follow;entry.resize(); } else {entry.fit();if(entry.follow) {v.w=Math.min(v.w,220);entry.resize();entry.centerDriver();}} controls(entry);
    const tools=el.querySelector('.map-tools'); for (const [text,f] of [['+',1/1.2],['−',1.2]]) { const btn=document.createElement('button'); btn.type='button'; btn.textContent=text; btn.setAttribute('aria-label',text==='+'?'Acercar mapa':'Alejar mapa'); btn.onclick=() => zoom(f); tools.appendChild(btn); }
  }
  function remove(entry) { const saved=entry.map?{center:entry.map.getCenter(),zoom:entry.map.getZoom(),follow:entry.follow}:viewports.get(entry.key) || {}; viewports.set(entry.key,{...saved,follow:entry.follow,expanded:entry.el.classList.contains('map-expanded'),focused:document.activeElement===entry.el}); clearTimeout(entry.signalTimer);entry.cleanup?.(); entry.observer?.disconnect(); entry.map?.remove(); }
  L.maps.MapManager={
    isInteracting() { return [...maps.values()].some(entry => entry.interacting); },
    destroy() { for (const entry of maps.values()) remove(entry); maps.clear(); },
    mount(id,config) { const el=document.getElementById(id); if (!el) return; const prior=maps.get(id); if (prior) remove(prior); const entry={el,config,key:config.key || id,map:null,follow:!!config.followDriver,driverMarkers:new Map()}; entry.saved=viewports.get(entry.key); maps.set(id,entry); try { if (window.L) leaflet(entry); else fallback(entry); } catch (e) { entry.cleanup?.(); entry.observer?.disconnect(); entry.map?.remove(); entry.map=null; fallback(entry); } if(config.orderId) {const tick=()=>{const t=L.core.DatabaseService.state.orders.find(o=>o.id===config.orderId)?.tracking;if(t)this.telemetry(config.orderId,t);entry.signalTimer=setTimeout(tick,1000);};tick();} if (entry.saved?.focused) entry.el.focus?.({preventScroll:true}); if (config.error) { const warning=document.createElement('div'); warning.className='map-warning'; warning.textContent=config.error; el.appendChild(warning); } },
    collapse(id){const entry=maps.get(id);if(entry?.el.classList.contains('map-expanded')){entry.el.classList.remove('map-expanded');entry.expandButton.textContent='Ampliar';entry.expandButton.setAttribute('aria-pressed','false');entry.resize();}},
    selectLocation(lat,lng,recenter=false) { const entry=maps.get('location-map'); if (!entry) return; entry.customerMarker?.setLatLng([lat,lng]); if (entry.map && recenter) entry.map.panTo([lat,lng]); if (!entry.map) { const p=entry.project([lat,lng]),marker=entry.el.querySelector('[data-map-marker="customer"]'); marker?.setAttribute('cx',p[0]); marker?.setAttribute('cy',p[1]); } },
    telemetry(orderId,t) { document.querySelectorAll('[data-telemetry="'+orderId+'"]').forEach(el=>{const key=el.dataset.telemetryMetric;if(key==='signal')el.textContent=L.services.TrackingService.signal(t,L.core.DatabaseService.state.orders.find(o=>o.id===orderId)?.status);if(key==='updated')el.textContent=t.updatedAt?L.time(t.updatedAt)+' · hace '+Math.max(0,Math.floor((Date.now()-Date.parse(t.updatedAt))/1000))+' s':'Sin posición';if(key==='coordinates')el.textContent=t.position.map(n=>n.toFixed(6)).join(', ');if(key==='heading')el.textContent=Math.round(t.heading || 0)+'°';if(key==='sequence')el.textContent=t.sequence || 0;}); },
    frame(orderId,t) {
      const o=L.core.DatabaseService.getOrder(orderId),now=performance.now();
      for (const entry of maps.values()) {
        if (entry.map) { const marker=entry.driverMarkers.get(o.driverId);marker?.setLatLng(t.position);const d=L.services.DriverService.get(o.driverId);marker?.setTooltipContent?.('<strong>'+E(d.name)+'</strong><br>'+E(o.id)+' · '+E(L.core.StateMachine.label(o.status))+'<br>'+E(t.leg==='restaurant'?o.restaurantName:o.address)+'<br>'+E(L.services.TrackingService.signal(t,o.status))+' · ETA '+t.eta+' min');const icon=marker?.getElement?.()?.querySelector('.driver-bearing');if(icon)icon.style.transform='rotate('+(t.heading || 0)+'deg)'; }
        else {const marker=entry.el.querySelector('[data-map-marker="'+o.driverId+'"]');if(marker){const p=entry.project(t.position);marker.setAttribute('cx',p[0]);marker.setAttribute('cy',p[1]);}}
        if(entry.fleetVectors?.has(orderId)){const points=L.maps.Routes.completed(t.points,t.progress).map(entry.project).map(p=>p.join(',')).join(' ');entry.fleetVectors.get(orderId).setAttribute('points',points);}
        if(entry.fleetTrails?.has(orderId)){entry.fleetFrames ||= new Map();if(now-(entry.fleetFrames.get(orderId) ?? -Infinity)>=250 || t.progress===1){entry.fleetFrames.set(orderId,now);entry.fleetTrails.get(orderId).setLatLngs(L.maps.Routes.completed(t.points,t.progress));}}
        if(entry.config.orderId===orderId && (entry.lastFrame==null || now-entry.lastFrame>=(L.services.TrackingService.parameters.followIntervalMs || 250) || t.progress===1)) { entry.lastFrame=now; if(entry.follow && !entry.interacting)entry.centerDriver();if(entry.config.hasPosition){const points=L.maps.Routes.completed(t.points,t.progress);entry.trail?.setLatLngs(points);entry.updateTrail?.(points);}this.telemetry(orderId,t); }
      }
      document.querySelectorAll('[data-track="'+orderId+'"]').forEach(el=>{const key=el.dataset.metric;if(key==='scene'){el.style.setProperty('--journey',t.progress);return;}if(key==='progress'){el.style.width=t.progress*100+'%';el.parentElement.setAttribute('aria-valuenow',Math.round(t.progress*100));}else if(key==='street')el.textContent=L.services.TrackingService.currentStep(t)?.name || 'Llegada al destino';else if(key==='eta')el.textContent=t.eta+' min';else if(key==='distance')el.textContent=t.remainingKm.toFixed(2)+' km';else if(key==='percent')el.textContent=Math.round(t.progress*100)+'%';});
    },
    overview(options={}) {
      const s=L.core.DatabaseService.state,active=s.orders.filter(o=>!L.core.StateMachine.terminal.includes(o.status)),B=L.ui.button;
      const stateLabel=d=>({AVAILABLE:'Libre para recibir ofertas',OFFLINE:'Desconectado',OFFERED:'Oferta pendiente',ACCEPTED:'Asignado',PICKING_UP:'Va a recoger',DELIVERING:'Lleva un pedido'})[d.status] || d.status;
      const markers=[...s.restaurants.map(r=>({...r,tooltip:'<strong>'+E(r.name)+'</strong><br>'+E(r.address)+'<br>'+(r.open?'Abierto':'Cerrado')+' · '+active.filter(o=>o.restaurantId===r.id).length+' pedidos activos',popup:options.fleet?'<div class="fleet-popup"><strong>'+E(r.name)+'</strong><p>'+E(r.address)+'</p><p>'+(r.open?'Cocina abierta':'Cocina cerrada')+'</p>'+B('contact-role','Contactar cocina',{actor:'restaurant',recipient:r.id},'notifications')+'</div>':null})),
        ...s.drivers.map(d=>{const o=active.find(o=>o.driverId===d.id || o.offeredDriverId===d.id),destination=o?(o.tracking?.leg==='customer' || o.status==='PICKED_UP'?o.address:o.restaurantName):'Sin entrega asignada',info='<strong>'+E(d.name)+'</strong><br>'+E(d.vehicle)+'<br>'+E(stateLabel(d))+'<br>'+E(destination);return {...d,driver:true,tooltip:info,popup:options.fleet?'<div class="fleet-popup">'+info+(o?'<p>'+E(o.id)+' · '+E(L.core.StateMachine.label(o.status))+'</p>'+B('watch-order','Seguir esta entrega',{id:o.id},'route'):'<p>Sin entrega asignada.</p>')+B('contact-role','Mensaje al repartidor',{actor:'driver',recipient:d.id,orderId:o?.id || ''},'notifications')+'</div>':null};}),
        ...active.map(o=>({id:o.id,lat:o.lat,lng:o.lng,name:o.id,customer:true,tooltip:'<strong>'+E(o.id)+'</strong><br>'+E(o.address)+'<br>'+E(L.core.StateMachine.label(o.status)),popup:options.fleet?'<div class="fleet-popup"><strong>'+E(o.id)+'</strong><p>Destino: '+E(o.address)+'</p><p>'+E(L.core.StateMachine.label(o.status))+'</p>'+B('watch-order','Seguir entrega',{id:o.id},'route')+'</div>':null}))];
      const routes=[],errors=[];
      if(options.fleet)for(const o of active){const driverId=o.driverId || o.offeredDriverId;if(!driverId)continue;const d=s.drivers.find(d=>d.id===driverId),r=s.restaurants.find(r=>r.id===o.restaurantId),t=o.tracking,customer=t?.leg==='customer' || o.status==='PICKED_UP';try{const plan=customer?this.order(o).plan:t?.routePlan || L.maps.Routes.plan([d.lat,d.lng],[r.lat,r.lng],L.maps.StreetNetwork.profile(d.vehicle)),future=customer?null:L.maps.Routes.plan([r.lat,r.lng],[o.lat,o.lng],L.maps.StreetNetwork.profile(d.vehicle));if(!plan)L.fail('No hay ruta disponible para este destino',422);routes.push({orderId:o.id,driverId,plan,future,progress:t?.progress || 0,running:!!t?.running,name:o.id+' · '+(customer?'Entrega a '+o.address:'Recogida en '+r.name),status:o.status,destination:customer?o.address:r.name,eta:t?.eta});}catch(e){errors.push(o.id+': '+e.message);}}
      return {markers,routes,fleet:!!options.fleet,key:options.fleet?'operations-fleet':undefined,errors};
    },
    order(o) { const r=L.services.CatalogService.restaurant(o.restaurantId),d=o.driverId?L.services.DriverService.get(o.driverId):null,t=o.tracking,pendingCustomer=o.status==='PICKED_UP' && t?.leg==='restaurant'; const markers=[{...r},{lat:o.lat,lng:o.lng,name:o.customerName,customer:true}]; if (d) markers.push({...d,driver:true,lat:t?.position[0] ?? d.lat,lng:t?.position[1] ?? d.lng}); let plan=pendingCustomer?null:t?.routePlan,error; if (!plan) try { plan=L.maps.Routes.plan([r.lat,r.lng],[o.lat,o.lng],L.maps.StreetNetwork.profile(d?.vehicle)); } catch (e) { error=e.message; } const hasPosition=!!t && !pendingCustomer;return {key:'order-'+o.id+'-'+(pendingCustomer?'customer-preview':t?.sessionId || t?.leg || 'reference'),orderId:o.id,markers,plan,route:plan?.points,error,hasPosition,position:t?.position,canFollow:hasPosition && !L.core.StateMachine.terminal.includes(o.status),progress:t?.progress || 0,followDriver:hasPosition && !L.core.StateMachine.terminal.includes(o.status) && L.services.TrackingService.parameters.followDriver}; }
  };
  L.EventBus.on('tracking:frame',e => L.maps.MapManager.frame(e.orderId,e.tracking));
})(window.LlajtaVoy);
