/* Verificaciones ejecutables del núcleo. El host aporta las APIs estándar
   de almacenamiento y reloj; nunca se usan datos del navegador del usuario. */
(function (L) {
  'use strict';
  L.verifyCore = async function () {
    const DB = L.core.DatabaseService, G = L.core.ApiGateway, B = L.core.EventBroker, results = [];
    const check = (name,condition) => { if (!condition) throw new Error('FALLÓ: '+name); results.push({ name,status:'PASS' }); };
    const waitUntil = async fn => { const end = Date.now()+5000; while (!fn()) { if (Date.now()>end) throw new Error('Tiempo de espera agotado'); await new Promise(r => setTimeout(r,15)); } };
    const request = async (method,path,data,context) => (await G.request(method,path,data || {},context || {actor:'admin'})).data;
    const fails = async (fn,status) => { try { await fn(); return false; } catch (e) { return e.status===status; } };
    const c={actor:'client',customerId:'c1'}, r={actor:'restaurant',restaurantId:'r1'};
    const data={restaurantId:'r1',items:[{productId:'p1',quantity:2}],customerName:'Andrea',address:'Avenida Santa Cruz, Recoleta',lat:-17.378,lng:-66.151,paymentMethod:'QR',notes:'Llajua por separado'};
    DB.init();
    B.subscribe('q.restaurant.orders',['order.created'],'RestaurantService',e => L.services.RestaurantService.receive(e));
    B.subscribe('q.dispatch.orders',['order.ready'],'DispatchService',e => L.services.DispatchService.search(e));
    B.subscribe('q.driver.offers',['driver.offer.created'],'DriverService',e => L.services.DriverService.consumeOffer(e));
    B.subscribe('q.notifications',L.services.NotificationService.patterns,'NotificationService',e => L.services.NotificationService.consume(e));
    B.subscribe('q.analytics',['#'],'AnalyticsService',e => L.services.AnalyticsService.consume(e));
    B.subscribe('q.audit',['#'],'AuditService',e => L.services.AuditService.consume(e));
    B.subscribe('q.payments',['payment.*'],'PaymentService',e => L.services.PaymentService.consume(e));
    G.init(); DB.reset();
    check('KPIs iniciales derivados sin pedidos inventados',L.services.AnalyticsService.summary().active===0 && DB.getOrders().length===0);
    const order = await request('POST','/api/orders',data,c); await waitUntil(() => order.status==='SENT_TO_RESTAURANT');
    check('Checkout gateway, precio desde catálogo y pago aprobado',order.total===72 && DB.state.payments[0].status==='APPROVED' && DB.state.requests.some(r => r.method==='POST' && r.endpoint==='/api/orders' && r.status===201));
    const keys = DB.getEvents().filter(e => e.correlationId===order.correlationId).map(e => e.routingKey);
    check('Secuencia payment.processing → approved → order.created',keys.indexOf('payment.processing')<keys.indexOf('payment.approved') && keys.indexOf('payment.approved')<keys.indexOf('order.created'));
    check('Mismo objeto de pedido en actor restaurante',await request('GET','/api/orders/'+order.id,{},r)===order);
    check('Otro cliente no accede al pedido',await fails(() => request('GET','/api/orders/'+order.id,{},{actor:'client',customerId:'c2'}),403));
    check('Otro restaurante no modifica el pedido',await fails(() => request('PATCH','/api/orders/'+order.id+'/status',{status:'ACCEPTED'},{actor:'restaurant',restaurantId:'r2'}),403));
    check('Producto de otro establecimiento no modificable',await fails(() => request('PATCH','/api/products/p4',{price:1},r),403));
    for (const status of ['ACCEPTED','PREPARING','READY_FOR_PICKUP']) await request('PATCH','/api/orders/'+order.id+'/status',{status},r);
    await waitUntil(() => order.offeredDriverId); const firstDriver = order.offeredDriverId;
    check('Despacho automático y evento de búsqueda',order.status==='DRIVER_SEARCHING' && DB.getEvents().some(e => e.routingKey==='driver.search.started'));
    await request('POST','/api/offers/'+order.id+'/reject',{}, {actor:'driver',driverId:firstDriver});
    check('Oferta rechazada pasa al siguiente candidato',order.offeredDriverId && order.offeredDriverId!==firstDriver && DB.getEvents().some(e => e.routingKey==='driver.offer.rejected'));
    const dc={actor:'driver',driverId:order.offeredDriverId}; await request('POST','/api/offers/'+order.id+'/accept',{},dc);
    check('Asignación con contexto de repartidor',order.status==='DRIVER_ASSIGNED' && order.driverId===dc.driverId);
    check('No permite recoger antes de llegar',await fails(() => request('PATCH','/api/orders/'+order.id+'/status',{status:'PICKED_UP'},dc),409));
    await request('POST','/api/tracking/'+order.id,{leg:'restaurant'},dc);
    await waitUntil(() => order.tracking.progress>.15); const position = L.copy(order.tracking.position), initialDistance=order.tracking.remainingKm;
    await request('PATCH','/api/tracking/'+order.id,{},dc); DB.flush(); const orderId=order.id; DB.init(); const restored=DB.getOrder(orderId);
    check('Persistencia de posición, pedido y pago al recargar capa de datos',restored.tracking.position[0]===position[0] && DB.state.payments.length===1 && restored.id===orderId);
    await request('POST','/api/tracking/'+restored.id,{leg:'restaurant'},dc); await waitUntil(() => restored.tracking.arrived);
    check('Ruta continua termina en restaurante y distancia disminuye',restored.tracking.remainingKm<initialDistance && restored.tracking.progress===1 && restored.tracking.position[0]===L.services.CatalogService.restaurant('r1').lat);
    await request('PATCH','/api/orders/'+restored.id+'/status',{status:'PICKED_UP'},dc); await request('POST','/api/tracking/'+restored.id,{leg:'customer'},dc); await waitUntil(() => restored.tracking.arrived);
    check('GPS a cliente, ETA cero y ARRIVING',restored.status==='ARRIVING' && restored.tracking.eta===0 && restored.tracking.position[0]===data.lat && DB.getEvents().some(e => e.routingKey==='tracking.position.updated'));
    await request('PATCH','/api/orders/'+restored.id+'/status',{status:'DELIVERED'},dc);
    check('Entrega completa libera repartidor y actualiza KPIs',restored.status==='DELIVERED' && L.services.DriverService.get(dc.driverId).status==='AVAILABLE' && L.services.AnalyticsService.summary().delivered===1 && L.services.AnalyticsService.summary().sales===72);
    check('Estado terminal no regresa a preparación',await fails(() => request('PATCH','/api/orders/'+restored.id+'/status',{status:'PREPARING'},r),409));
    await waitUntil(() => !DB.state.messages.some(m => ['READY','PROCESSING','RETRY'].includes(m.status)));
    check('Eventos del pedido conservan correlationId',DB.getEvents().filter(e => e.payload.orderId===restored.id).every(e => e.correlationId===restored.correlationId));
    const notices=DB.getNotifications(); check('Notificaciones de entrega generadas sin duplicados',notices.some(n => n.text==='Pedido entregado') && new Set(notices.map(n => n.sourceEventId)).size===notices.length);
    L.services.NotificationService.read(notices[0].id,true); DB.init(); check('Lectura de notificaciones persistida',DB.getNotifications()[0].read===true);
    DB.reset(); DB.change(s => { s.flags.rejectPayment=true; }); const rejected=await request('POST','/api/orders',data,c); check('Rechazo de pago real sin venta ni order.created',rejected.status==='PAYMENT_REJECTED' && L.services.AnalyticsService.summary().sales===0 && !DB.getEvents().some(e => e.routingKey==='order.created'));
    DB.reset(); DB.change(s => { s.flags.failNotification=true; }); const failedNoticeOrder=await request('POST','/api/orders',data,c); await waitUntil(() => DB.getEvents().some(e => e.routingKey==='notification.failed') && DB.getNotifications().some(n => n.status==='SENT'));
    check('Notificación falla, reintenta y envía sin duplicar',DB.getNotifications().filter(n => n.orderId===failedNoticeOrder.id).length===1 && B.stats().nack>=1 && B.stats().retry>=1);
    await request('PATCH','/api/orders/'+failedNoticeOrder.id+'/status',{status:'CANCELLED'},c); check('Cancelación revierte pago y venta',DB.state.payments[0].status==='REFUNDED' && L.services.AnalyticsService.summary().sales===0);
    DB.reset(); await request('POST','/api/admin/scenario',{action:'NACK'}); await waitUntil(() => B.stats().ack>0 && B.stats().nack===1 && !DB.state.messages.some(m => m.status==='RETRY')); check('NACK → Retry → ACK observable',B.stats().retry===1);
    DB.reset(); await request('POST','/api/admin/scenario',{action:'RETRY'}); await waitUntil(() => B.stats().nack===2 && !DB.state.messages.some(m => ['READY','RETRY','PROCESSING'].includes(m.status))); check('Dos fallos, tercer intento ACK',DB.state.messages.find(m => m.queue==='q.audit').attempts===3);
    DB.reset(); await request('POST','/api/admin/scenario',{action:'DLQ'}); await waitUntil(() => B.stats().dlq===1); const dead=DB.state.messages.find(m => m.status==='DLQ'); check('DLQ conserva error y tres intentos',dead.attempts===3 && !!dead.error); await request('POST','/api/admin/dlq/'+dead.id); await waitUntil(() => dead.status==='ACK'); check('Reprocesar DLQ sin duplicar evento',B.stats().dlq===0 && DB.getEvents().length===1);
    DB.reset(); await request('POST','/api/admin/scenario',{action:'offline',service:'OrderService'}); check('Servicio caído responde 503',await fails(() => request('POST','/api/orders',data,c),503)); await request('POST','/api/admin/scenario',{action:'restore',service:'OrderService'}); check('Servicio restaurado permite crear pedido',!!(await request('POST','/api/orders',data,c)).id);
    DB.reset(); DB.change(s => { s.unavailable=['PaymentService']; }); check('Caída del pago interno no crea pedido parcial',await fails(() => request('POST','/api/orders',data,c),503) && DB.getOrders().length===0);
    DB.reset(); let limited=0; for (let i=0;i<65;i++) try { await request('GET','/api/restaurants'); } catch (error) { if (error.status===429) limited++; else throw error; } check('60 requests permitidos y 5 bloqueados; 65 logs',limited===5 && DB.state.requests.length===65);
    DB.reset(); const original=DB.getProducts('r1')[0]; await request('PATCH','/api/products/'+original.id,{price:33,available:false},r); check('Menú cambia y producto agotado no comprable',original.price===33 && !original.available && await fails(() => request('POST','/api/orders',data,c),422));
    DB.reset(); check('Restablecimiento elimina datos operativos y conserva catálogo editado',DB.getOrders().length===0 && DB.getEvents().length===0 && DB.getDrivers().every(d => d.status==='AVAILABLE') && DB.getProducts('r1')[0].price===33);
    B.stop(); L.services.TrackingService.stopAll();
    return results;
  };
})(window.LlajtaVoy);
