/* Instrumentación de DOM y API Leaflet: no sustituye una prueba visual. */
(function () {
  'use strict';
  window.verifyLlajtaMaps=function(sources,streetSource,landmarkSource) {
    let tick=0;const performance={now:()=>tick};
    const results=[],elements=new Map(),instances=[],markers=[],lines=[];
    const check=(name,value) => { if (!value) throw Error(name); results.push({name,status:'PASS'}); };
    const node=() => ({children:[],attrs:{},style:{},classList:{set:new Set(),add(c){this.set.add(c);},remove(c){this.set.delete(c);},contains(c){return this.set.has(c);},toggle(c){if(this.set.has(c)){this.set.delete(c);return false;}this.set.add(c);return true;}},appendChild(c){this.children.push(c);},setAttribute(k,v){this.attrs[k]=v;},getBoundingClientRect:() => ({left:0,top:0,width:600,height:340}),setPointerCapture(){},querySelector(selector){if(selector==='.map-tools')return this.children.find(c=>c.className==='map-tools');if(selector==='svg'){this.svg ||= node();return this.svg;} if(selector.startsWith('[data-map-marker')) {this.marker ||= node();return this.marker;} return null;}});
    const document={createElement:node,createElementNS:()=>node(),getElementById(id){if(!elements.has(id))elements.set(id,node());return elements.get(id);},querySelectorAll:() => []};
    const window={location:{protocol:'file:'},LlajtaVoy:{maps:{},core:{},services:{},now:() => new Date().toISOString(),escape:String,ui:{icon:() => '<svg></svg>'},EventBus:{on(name,fn){this[name]=fn;},emit(){}}}};
    const LV=window.LlajtaVoy;
    eval(sources['js/maps/cochabamba.js']);eval(sources['js/seed-data.js']);eval(streetSource);eval(landmarkSource);
    LV.core.DatabaseService={state:LV.seed(),getOrder(id){return this.state.orders.find(o=>o.id===id);}};
    LV.core.StateMachine={terminal:['DELIVERED'],label:x=>x || ''};LV.services.CatalogService={restaurant:id=>LV.core.DatabaseService.state.restaurants.find(r=>r.id===id)};LV.services.DriverService={get:id=>LV.core.DatabaseService.state.drivers.find(d=>d.id===id)};
    window.L={
      map(el,options){const m={options,handlers:{},center:[0,0],zoom:14,attributionControl:{addAttribution(){}},setView(p,z){this.center=Array.isArray(p)?p:[p.lat,p.lng];this.zoom=z;return this;},fitBounds(bounds){this.bounds=bounds;this.fits=(this.fits || 0)+1;this.zoom=14;return this;},getBoundsZoom(){return el.classList.contains('map-expanded')?14:12;},setMinZoom(z){this.minZoom=z;return this;},panTo(p){this.center=p;this.pans=(this.pans || 0)+1;return this;},getCenter(){return {lat:this.center[0],lng:this.center[1]};},getZoom(){return this.zoom;},getSize(){return {x:600,y:340};},latLngToContainerPoint(){return {x:300,y:180};},on(name,fn){this.handlers[name]=fn;return this;},invalidateSize(){this.resized=true;},remove(){this.removed=true;}};instances.push(m);return m;},
      layerGroup(){return {addTo(){return this;},clearLayers(){}};},control:{scale:()=>({addTo(){}})},DomEvent:{disableClickPropagation(){},disableScrollPropagation(){}},latLngBounds:p=>p,divIcon:o=>o,
      marker(p,o){const m={position:p,options:o,handlers:{},addTo(){return this;},bindTooltip(text){this.tooltip=text;return this;},setTooltipContent(text){this.tooltip=text;return this;},bindPopup(text){this.popup=text;return this;},on(name,fn){this.handlers[name]=fn;return this;},getLatLng(){return {lat:this.position[0],lng:this.position[1]};},setLatLng(p){this.position=p;return this;}};markers.push(m);return m;},
      polyline(p,o){const line={points:p,options:o,addTo(){return this;},setStyle(s){this.style=s;},setLatLngs(p){this.points=p;return this;},bindTooltip(text){this.tooltip=text;return this;},bindPopup(text){this.popup=text;return this;}};lines.push(line);return line;},polygon(p,o){return this.polyline(p,o);},rectangle(p,o){return this.polyline(p,o);},
      tileLayer(){throw Error('No deben solicitarse tiles');}
    };
    LV.maps.StreetNetwork={profile:()=> 'motorcycle',plan:(a,b)=>({points:[a,b],totalKm:1,segments:[],steps:[]})};eval(sources['js/ui/components.js']);eval(sources['js/maps/routes.js']);LV.services.TrackingService={parameters:{followDriver:true},signal:()=>'',currentStep:()=>null};eval(sources['js/maps/map-manager.js']);const M=LV.maps.MapManager,config=M.overview();M.mount('home-map',config);
    check('file:// crea el mapa Leaflet con geometría local',instances.length===1 && lines.some(l=>Array.isArray(l.points[0]?.[0])));
    check('Arrastre, rueda, teclado y pellizco están habilitados',instances[0].options.dragging && instances[0].options.scrollWheelZoom && instances[0].options.keyboard && instances[0].options.touchZoom);
    check('Los nueve actores iniciales aparecen como marcadores',markers.filter(m=>m.options.icon.className.startsWith('pin')).length===9);
    check('Las calles se agrupan para evitar miles de capas',lines.length<400);
    instances[0].setView([-17.37,-66.17],17);M.destroy();M.mount('home-map',config);
    check('La actualización de la vista conserva centro y zoom',instances[1].zoom===17 && instances[1].center[0]===-17.37);
    let selection;const loc={markers:[{lat:-17.378,lng:-66.151,name:'Destino',customer:true}],onSelect:(a,b)=>{selection=[a,b];M.selectLocation(a,b);}};M.mount('location-map',loc);const map=instances.at(-1),pin=markers.findLast(m=>m.options.draggable);
    map.handlers.click({latlng:{lat:-17.38,lng:-66.155}});
    check('El clic mueve el destino sin reconstruir ni recentrar el mapa',selection[0]===-17.38 && pin.position[1]===-66.155 && !map.removed && !map.pans);
    pin.position=[-17.379,-66.15];pin.handlers.dragend();check('Arrastrar el pin actualiza las coordenadas del destino',selection[0]===-17.379);
    const t={position:[-17.385,-66.156],progress:.4,remainingKm:1.2,eta:3,points:[[-17.3895,-66.1585],[-17.3936,-66.1567]]};LV.core.DatabaseService.state.orders.push({id:'test',restaurantId:'r1',restaurantName:'Cocina QA',customerName:'Cliente QA',address:'Destino QA',customerId:'c1',status:'DRIVER_ASSIGNED',lat:-17.378,lng:-66.151,driverId:'d1',tracking:t});M.mount('tracking-map',{...config,key:'test',orderId:'test',hasPosition:true,position:t.position,followDriver:true,route:[[-17.3895,-66.1585],[-17.3936,-66.1567]]});const trackingMap=instances.at(-1);M.frame('test',t);
    check('Tracking sigue al repartidor por defecto desde el primer cuadro',markers.some(m=>m.options.icon.className.startsWith('pin driver') && m.position===t.position) && trackingMap.pans>0 && trackingMap.zoom===16);
    const pansBefore=trackingMap.pans;M.frame('test',t);check('La cámara no recentra en cada frame consecutivo',trackingMap.pans===pansBefore);
    const tools=document.getElementById('tracking-map').querySelector('.map-tools'),follow=tools.children.find(b=>b.textContent==='Seguir repartidor');follow.onclick({stopPropagation(){}});follow.onclick({stopPropagation(){}});M.frame('test',t);
    check('Seguir recentra y arrastrar el mapa desactiva el seguimiento',trackingMap.pans>0 && follow.attrs['aria-pressed']==='true');trackingMap.handlers.dragstart();tick+=300;const beforeDragPans=trackingMap.pans;M.frame('test',t);check('Después de arrastrar se puede explorar sin seguimiento automático',follow.attrs['aria-pressed']==='false' && trackingMap.pans===beforeDragPans);
    tools.children.find(b=>b.textContent==='Ampliar').onclick({stopPropagation(){}});check('Ampliar ajusta el contenedor y recalcula su tamaño',document.getElementById('tracking-map').classList.contains('map-expanded') && trackingMap.resized);
    check('Mientras se arrastra el mapa, el shell detecta interacción activa',M.isInteracting());trackingMap.handlers.dragend();check('El final del gesto libera las actualizaciones pendientes',!M.isInteracting());
    M.destroy();elements.set('tracking-map',node());M.mount('tracking-map',{...config,key:'test',orderId:'test'});check('Actualizar la vista conserva el modo ampliado y el seguimiento desactivado',document.getElementById('tracking-map').classList.contains('map-expanded') && document.getElementById('tracking-map').querySelector('.map-tools').children.find(b=>b.textContent==='Seguir repartidor').attrs['aria-pressed']==='false');
    M.mount('new-leg',{...config,key:'test-customer-leg',orderId:'test',hasPosition:true,position:t.position,followDriver:true,route:t.points});const newMap=instances.at(-1);check('Un nuevo tramo restablece seguimiento y zoom inicial',newMap.zoom===16 && newMap.center===t.position && document.getElementById('new-leg').querySelector('.map-tools').children.find(b=>b.textContent==='Seguir repartidor').attrs['aria-pressed']==='true');
    M.destroy();const order=LV.core.DatabaseService.state.orders[0];t.routePlan={points:t.points,totalKm:1};t.leg='restaurant';t.running=true;LV.core.DatabaseService.state.drivers[0].status='PICKING_UP';const fleet=M.overview({fleet:true});M.mount('operations-map',fleet);const fleetMap=instances.at(-1),fleetTools=document.getElementById('operations-map').querySelector('.map-tools');check('Flota incluye ruta asignada y el tramo futuro al destino',fleet.routes.length===1 && fleet.routes[0].future && fleet.routes[0].driverId==='d1');check('Pins de flota muestran estado, destino y contacto local',markers.some(m=>m.options.icon.className==='pin driver busy' && m.tooltip.includes('Cocina QA') && m.popup.includes('contact-role') && m.popup.includes('watch-order')));fleetTools.children.find(b=>b.textContent==='Ampliar').onclick({stopPropagation(){}});check('Ampliar flota encuadra el territorio en el nuevo tamaño',fleetMap.bounds[0][0]===LV.maps.StreetData.bounds.south && fleetMap.minZoom===14 && fleetMap.resized);const trail=lines.findLast(l=>l.options.color==='#537B59');tick+=300;t.progress=.7;M.frame('test',t);check('El avance actualiza también el rastro en el mapa de flota',trail.points.length>=2 && Math.abs(trail.points.at(-1)[0]-LV.maps.Routes.at(t.points,.7)[0])<.000001);M.collapse('operations-map');check('Seleccionar seguimiento permite cerrar la ampliación de flota',!document.getElementById('operations-map').classList.contains('map-expanded'));
    M.destroy();window.L=undefined;M.mount('fallback',loc);const el=document.getElementById('fallback'),svg=el.querySelector('svg'),before=svg.attrs.viewBox;svg.onwheel({deltaY:-1,clientX:300,clientY:170,preventDefault(){}});check('Sin Leaflet el respaldo vectorial permite zoom',svg.attrs.viewBox!==before && el.innerHTML.includes('OpenStreetMap'));
    const zoomed=svg.attrs.viewBox;svg.onpointerdown({pointerId:1,clientX:200,clientY:150});svg.onpointermove({pointerId:1,clientX:260,clientY:150});svg.onpointerup({pointerId:1,clientX:260,clientY:150});check('El respaldo permite arrastrar y no confunde el gesto con seleccionar',svg.attrs.viewBox!==zoomed && selection[0]===-17.379);
    M.mount('fallback-tracking',{...config,key:'fallback-trip',orderId:'test',hasPosition:true,position:t.position,followDriver:true,route:t.points});const fs=document.getElementById('fallback-tracking').querySelector('svg'),beforeFollow=fs.attrs.viewBox;t.position=[-17.38,-66.15];tick+=300;M.frame('test',t);check('El respaldo SVG también sigue posiciones y dibuja el rastro',fs.attrs.viewBox!==beforeFollow && fs.children.some(c=>c.attrs.stroke==='#537B59'));
    M.destroy();return results;
  };
})();
