(function (L) {
  const E = L.escape, I = L.ui.icon, DB = L.core.DatabaseService;
  L.ui.userError=error=>{if(error.status===503)return 'Esta función no está disponible por el momento. Intenta nuevamente más tarde.';return String(error.message || 'No pudimos completar la operación').replace(/PaymentService/g,'El servicio de pagos').replace(/OrderService/g,'El servicio de pedidos').replace(/TrackingService/g,'El seguimiento').replace(/CommunicationService/g,'Los mensajes');};
  L.ui.button = (action,label,data = {},icon,className = '') => '<button type="button" class="'+className+'" data-action="'+action+'" '+Object.entries(data).map(([key,value]) => 'data-'+key+'="'+E(value)+'"').join(' ')+'>'+(icon?I(icon):'')+'<span>'+label+'</span></button>';
  L.ui.badge = status => '<span class="badge '+(['DELIVERED','AVAILABLE','ACK','APPROVED','SENT'].includes(status)?'success':['PAYMENT_REJECTED','RESTAURANT_REJECTED','CANCELLED','DELIVERY_FAILED','DLQ','REJECTED','FAILED'].includes(status)?'danger':'')+'">'+E(({APPROVED:'Aprobado',REJECTED:'Rechazado',ASSIGNED:'Asignado',SENT:'Enviado',FAILED:'No enviado',AVAILABLE:'Disponible',OFFLINE:'Desconectado',OFFERED:'Oferta pendiente',ACCEPTED:'Aceptado',PICKING_UP:'Recogiendo pedido',DELIVERING:'Entregando',PROCESSING:'Procesando',REFUNDED:'Reembolsado'})[status] || L.core.StateMachine.label(status))+'</span>';
  L.ui.kpis = entries => '<div class="kpis">'+entries.map(([label,value,icon]) => '<article class="kpi"><div class="kpi-icon">'+I(icon || 'monitoring')+'</div><div><small>'+label+'</small><strong>'+value+'</strong></div></article>').join('')+'</div>';
  L.ui.empty = (title,text,action) => '<div class="empty">'+I('receipt_long')+'<h3>'+title+'</h3><p>'+text+'</p>'+(action || '')+'</div>';
  L.ui.orderCard = (o,actions = '') => '<article class="order-card"><div class="section-head"><strong>'+o.id+'</strong>'+L.ui.badge(o.status)+'</div><small>'+L.time(o.createdAt)+' · '+E(o.customerName)+' · '+E(o.restaurantName)+'</small><ul class="order-items">'+o.items.map(i => '<li><span>'+i.quantity+' × '+E(i.name)+'</span><strong>'+L.money(i.quantity*i.price)+'</strong></li>').join('')+'</ul><p class="muted">'+E(o.address)+'</p>'+(o.notes?'<p class="notes">'+E(o.notes)+'</p>':'')+'<div class="section-head"><small>'+E(o.paymentMethod)+'</small><strong>'+L.money(o.total)+'</strong></div><div class="actions">'+actions+'</div></article>';
  L.ui.scenarios = () => '<section class="panel"><div class="section-head"><div><span class="eyebrow">CONTROL DE ESCENARIOS</span><h3>Observa cómo responde el sistema</h3></div>'+I('tune')+'</div><p class="muted">Pago, notificación y oferta afectan la próxima operación correspondiente. NACK, Retry y DLQ envían un mensaje al consumidor de auditoría.</p><div class="scenario-grid">'+[['rejectPayment','Rechazar próximo pago'],['failNotification','Fallar próxima notificación'],['rejectOffer','Repartidor rechaza oferta'],['NACK','Forzar NACK'],['RETRY','Forzar Retry'],['DLQ','Enviar a DLQ']].map(([key,label]) => L.ui.button('scenario',label,{key},'tune')).join('') +L.ui.button('burst','Generar ráfaga',{},'monitoring')+'</div><p class="muted">Prueba aislada: 65 solicitudes, límite 60/min. Los controles administrativos conservan su cuota.</p>'+(DB.state.lastBurst?'<p role="status">Última ráfaga: '+DB.state.lastBurst.accepted+' permitidas · '+DB.state.lastBurst.blocked+' bloqueadas (429).</p>':'')+'<div class="actions"><label>Servicio<select id="scenario-service">'+['OrderService','PaymentService','RestaurantService','DispatchService','NotificationService','TrackingService','CatalogService','DriverService','CommunicationService'].map(s => '<option>'+s+'</option>').join('')+'</select></label>'+L.ui.button('service-offline','Servicio no disponible',{},'warning')+L.ui.button('service-restore','Restaurar servicio',{},'refresh')+'</div><p class="muted">Pendientes: '+(Object.keys(DB.state.flags).map(E).join(', ') || 'ninguno')+' · No disponibles: '+(DB.state.unavailable.map(E).join(', ') || 'ninguno')+'</p></section>';
})(window.LlajtaVoy);
