(function (L) {
  const E = L.escape, I = L.ui.icon, DB = L.core.DatabaseService;
  L.ui.button = (action,label,data = {},icon,className = '') => '<button type="button" class="'+className+'" data-action="'+action+'" '+Object.entries(data).map(([key,value]) => 'data-'+key+'="'+E(value)+'"').join(' ')+'>'+(icon?I(icon):'')+'<span>'+label+'</span></button>';
  L.ui.badge = status => '<span class="badge '+(['DELIVERED','AVAILABLE','ACK','APPROVED','SENT'].includes(status)?'success':['PAYMENT_REJECTED','RESTAURANT_REJECTED','CANCELLED','DELIVERY_FAILED','DLQ','REJECTED','FAILED'].includes(status)?'danger':'')+'">'+E(L.core.StateMachine.label(status))+'</span>';
  L.ui.kpis = entries => '<div class="kpis">'+entries.map(([label,value,icon]) => '<article class="kpi"><div class="kpi-icon">'+I(icon || 'monitoring')+'</div><div><small>'+label+'</small><strong>'+value+'</strong></div></article>').join('')+'</div>';
  L.ui.empty = (title,text,action) => '<div class="empty">'+I('receipt_long')+'<h3>'+title+'</h3><p>'+text+'</p>'+(action || '')+'</div>';
  L.ui.orderCard = (o,actions = '') => '<article class="order-card"><div class="section-head"><strong>'+o.id+'</strong>'+L.ui.badge(o.status)+'</div><small>'+L.time(o.createdAt)+' · '+E(o.customerName)+' · '+E(o.restaurantName)+'</small><ul class="order-items">'+o.items.map(i => '<li><span>'+i.quantity+' × '+E(i.name)+'</span><strong>'+L.money(i.quantity*i.price)+'</strong></li>').join('')+'</ul><p class="muted">'+E(o.address)+'</p>'+(o.notes?'<p class="notes">'+E(o.notes)+'</p>':'')+'<div class="section-head"><small>'+E(o.paymentMethod)+'</small><strong>'+L.money(o.total)+'</strong></div><div class="actions">'+actions+'</div></article>';
  L.ui.tracking = o => { const t = o.tracking, d = o.driverId ? L.services.DriverService.get(o.driverId) : null; return '<section class="panel"><div class="section-head"><h3>Tu entrega, en tiempo real</h3>'+L.ui.badge(o.status)+'</div><div class="map" id="tracking-map"></div><div class="tracking-info">'+(d?'<div class="avatar">'+E(d.name[0])+'</div><div><strong>'+E(d.name)+'</strong><small>'+E(d.vehicle)+' · '+(d.rating || 'Sin calificar')+'</small></div>':'<p>El repartidor aparecerá cuando acepte la oferta.</p>')+'</div><div class="tracking-metrics"><div><small>Tiempo estimado</small><strong data-track="'+o.id+'" data-metric="eta">'+(t?t.eta+' min':'Por confirmar')+'</strong></div><div><small>Distancia restante</small><strong data-track="'+o.id+'" data-metric="distance">'+(t?t.remainingKm.toFixed(2)+' km':'Por confirmar')+'</strong></div><div><small>Recorrido</small><strong data-track="'+o.id+'" data-metric="percent">'+(t?Math.round(t.progress*100):0)+'%</strong></div></div><div class="progress" role="progressbar" aria-label="Progreso de la ruta" aria-valuemin="0" aria-valuemax="100" aria-valuenow="'+(t?Math.round(t.progress*100):0)+'"><i data-track="'+o.id+'" data-metric="progress" style="width:'+(t?t.progress*100:0)+'%"></i></div><small class="muted">'+(t?(t.leg === 'restaurant'?'Ruta al restaurante':'Ruta a tu dirección'):'Ruta de referencia')+' · Estimación sobre un recorrido local</small></section>'; };
  L.ui.scenarios = () => '<section class="panel"><div class="section-head"><div><span class="eyebrow">CONTROL DE ESCENARIOS</span><h3>Observa cómo responde el sistema</h3></div>'+I('tune')+'</div><p class="muted">Pago, notificación y oferta afectan la próxima operación correspondiente. NACK, Retry y DLQ envían un mensaje al consumidor de auditoría.</p><div class="scenario-grid">'+[['rejectPayment','Rechazar próximo pago'],['failNotification','Fallar próxima notificación'],['rejectOffer','Repartidor rechaza oferta'],['NACK','Forzar NACK'],['RETRY','Forzar Retry'],['DLQ','Enviar a DLQ']].map(([key,label]) => L.ui.button('scenario',label,{key},'tune')).join('')+L.ui.button('burst','Generar ráfaga',{},'monitoring')+'</div><div class="actions"><label>Servicio<select id="scenario-service">'+['OrderService','PaymentService','RestaurantService','DispatchService','NotificationService','TrackingService','CatalogService','DriverService'].map(s => '<option>'+s+'</option>').join('')+'</select></label>'+L.ui.button('service-offline','Servicio no disponible',{},'warning')+L.ui.button('service-restore','Restaurar servicio',{},'refresh')+'</div><p class="muted">Pendientes: '+(Object.keys(DB.state.flags).map(E).join(', ') || 'ninguno')+' · No disponibles: '+(DB.state.unavailable.map(E).join(', ') || 'ninguno')+'</p></section>';
})(window.LlajtaVoy);
