(function(L){
  'use strict';const E=L.escape;
  L.ui.tracking=(o,editable=false)=>{
    const t=o.tracking,d=o.driverId?L.services.DriverService.get(o.driverId):null,config=L.maps.MapManager.order(o),plan=config.plan;
    const preview=o.status==='PICKED_UP' && t?.leg==='restaurant',active=!!t && !preview,scale=t?.speedScale || 10,speed=t?.speedKmh || (L.maps.StreetNetwork.profile(d?.vehicle)==='bicycle'?12:24);
    const title=active && t.leg==='restaurant'?'Recorrido al restaurante':'Seguimiento de la entrega',percent=active?Math.round(t.progress*100):0;
    const metric=(key,text)=>'<strong data-track="'+o.id+'" data-metric="'+key+'">'+text+'</strong>';
    const ctx=L.app.context(),target=d?(ctx.actor==='driver'?(t?.leg==='customer'?{actor:'client',recipient:o.customerId,label:'Mensaje al cliente'}:{actor:'restaurant',recipient:o.restaurantId,label:'Mensaje a la cocina'}):{actor:'driver',recipient:d.id,label:'Mensaje al repartidor'}):null;
    const contact=target && !L.core.StateMachine.terminal.includes(o.status)?L.ui.button('contact-role',target.label,{actor:target.actor,recipient:target.recipient,orderId:o.id},'notifications'):'';
    const telemetry=(key,text)=>'<span data-telemetry="'+o.id+'" data-telemetry-metric="'+key+'">'+text+'</span>';
    const pace=active?'<div class="tracking-playback">'+(editable?'<label for="tracking-speed">Ritmo de demostración</label><select id="tracking-speed" data-order="'+o.id+'">'+[1,10,30].map(n=>'<option value="'+n+'" '+(scale===n?'selected':'')+'>'+n+'× '+(n===1?'Ritmo normal':'Acelerado')+'</option>').join('')+'</select>':'<strong>Reproducción '+scale+'×</strong>')+'<small>Velocidad de referencia: '+speed+' km/h · Sin tráfico en vivo</small></div>':'<p class="muted">'+(preview?'Pedido recogido. El repartidor debe iniciar la ruta al cliente.':'Ruta de referencia. La posición avanzará cuando el repartidor inicie el recorrido.')+'</p>';
    return '<section class="panel tracking-panel"><div class="section-head"><h3>'+title+'</h3><span class="badge">Posición simulada</span></div>'+L.ui.deliveryStage(o)+'<div class="map" id="tracking-map"></div><div class="route-key"><span>Ruta pendiente</span><span class="completed-key">Recorrido realizado</span><span>Acceso a la dirección</span></div><p class="tracking-camera-help">Seguimiento automático al iniciar cada tramo. Arrastra para explorar; pulsa Seguir repartidor para volver.</p>'+pace+'<div class="tracking-info">'+(d?'<div class="avatar">'+E(d.name[0])+'</div><div><strong>'+E(d.name)+'</strong><small>'+E(d.vehicle)+' · '+(d.rating || 'Sin calificar')+'</small></div>':'<p>El repartidor aparecerá cuando acepte la oferta.</p>')+'</div><div class="tracking-metrics"><div><small>'+(active && t.leg==='restaurant'?'ETA al restaurante':'ETA a la dirección')+'</small>'+metric('eta',L.core.StateMachine.terminal.includes(o.status)?'Pedido cerrado':active?t.eta+' min':'Por confirmar')+'</div><div><small>Distancia restante</small>'+metric('distance',active?t.remainingKm.toFixed(2)+' km':plan?plan.totalKm.toFixed(2)+' km':'Sin ruta')+'</div><div><small>Tramo recorrido</small>'+metric('percent',percent+'%')+'</div></div><div class="progress" role="progressbar" aria-label="Progreso del tramo" aria-valuemin="0" aria-valuemax="100" aria-valuenow="'+percent+'"><i data-track="'+o.id+'" data-metric="progress" style="width:'+percent+'%"></i></div>'+(active?'<div class="tracking-signal"><span class="status-dot"></span>'+telemetry('signal',L.services.TrackingService.signal(t,o.status))+'<small>Última posición: '+telemetry('updated',L.time(t.updatedAt))+'</small></div><div class="route-current">Ahora: '+metric('street',E(L.services.TrackingService.currentStep(t)?.name || (t.arrived?'Llegada al destino':'Recorrido detenido')))+'</div><details class="telemetry-details"><summary>Datos del seguimiento simulado</summary><dl><dt>Coordenadas</dt><dd>'+telemetry('coordinates',t.position.map(n=>n.toFixed(6)).join(', '))+'</dd><dt>Rumbo</dt><dd>'+telemetry('heading',Math.round(t.heading || 0)+'°')+'</dd><dt>Actualizaciones</dt><dd>'+telemetry('sequence',t.sequence || 0)+'</dd><dt>Origen</dt><dd>Demostración local · Sin GPS externo</dd></dl></details>':'')+(plan?'<details class="route-guide"><summary>Calles del recorrido · '+plan.totalKm.toFixed(2)+' km</summary><ol>'+plan.steps.map(s=>'<li>'+E(s.name)+'<span>'+Math.round(s.km*1000)+' m'+(s.type==='access'?' · Acceso aproximado a la calle':'')+'</span></li>').join('')+'</ol><small class="muted">Sentidos y accesos según el extracto OpenStreetMap. Sin tráfico ni cierres en vivo.</small></details>':'')+(t?.routeError?'<p class="form-error">'+E(t.routeError)+'</p>':'')+'<div class="actions">'+contact+'</div></section>';
  };
})(window.LlajtaVoy);
