(function (L) {
  'use strict';
  const E=L.escape;
  L.ui.tracking=(o,editable=false) => {
    const t=o.tracking,d=o.driverId?L.services.DriverService.get(o.driverId):null,plan=L.maps.MapManager.order(o).plan;
    const speedScale=t?.speedScale || 10,speedKmh=t?.speedKmh || (L.maps.StreetNetwork.profile(d?.vehicle)==='bicycle'?12:24);
    const title=t?.leg==='restaurant'?'Recorrido al restaurante':'Seguimiento de la entrega';
    const pace=t?'<div class="tracking-playback">'+(editable?'<label for="tracking-speed">Ritmo del recorrido</label><select id="tracking-speed" data-order="'+o.id+'">'+[1,10,30].map(n => '<option value="'+n+'" '+(speedScale===n?'selected':'')+'>'+n+'× '+(n===1?'Tiempo real':'Acelerado')+'</option>').join('')+'</select>':'<strong>Reproducción '+speedScale+'×</strong>')+'<small>Posición simulada · ETA de referencia a '+speedKmh+' km/h</small></div>':'<p class="muted">Ruta de referencia por calles. El seguimiento comienza cuando el repartidor inicia el recorrido.</p>';
    return '<section class="panel"><div class="section-head"><h3>'+title+'</h3>'+L.ui.badge(o.status)+'</div><div class="map" id="tracking-map"></div><div class="route-key"><span>Ruta por calles</span><span>Acceso a la dirección</span></div>'+pace+'<div class="tracking-info">'+(d?'<div class="avatar">'+E(d.name[0])+'</div><div><strong>'+E(d.name)+'</strong><small>'+E(d.vehicle)+' · '+(d.rating || 'Sin calificar')+'</small></div>':'<p>El repartidor aparecerá cuando acepte la oferta.</p>')+'</div><div class="tracking-metrics"><div><small>Tiempo estimado</small><strong data-track="'+o.id+'" data-metric="eta">'+(t?t.eta+' min':'Por confirmar')+'</strong></div><div><small>Distancia restante</small><strong data-track="'+o.id+'" data-metric="distance">'+(t?t.remainingKm.toFixed(2)+' km':plan?plan.totalKm.toFixed(2)+' km':'Sin ruta')+'</strong></div><div><small>Recorrido</small><strong data-track="'+o.id+'" data-metric="percent">'+(t?Math.round(t.progress*100):0)+'%</strong></div></div><div class="progress" role="progressbar" aria-label="Progreso de la ruta" aria-valuemin="0" aria-valuemax="100" aria-valuenow="'+(t?Math.round(t.progress*100):0)+'"><i data-track="'+o.id+'" data-metric="progress" style="width:'+(t?t.progress*100:0)+'%"></i></div>'+(t?'<div class="route-current">Ahora: <strong data-track="'+o.id+'" data-metric="street">'+E(L.services.TrackingService.currentStep(t)?.name || (t.progress>=1?'Llegada al destino':'Recorrido detenido'))+'</strong></div>':'')+(plan?'<details class="route-guide"><summary>Calles del recorrido · '+plan.totalKm.toFixed(2)+' km</summary><ol>'+plan.steps.map(s => '<li>'+E(s.name)+'<span>'+Math.round(s.km*1000)+' m'+(s.type==='access'?' · Acceso aproximado desde/hasta la calle':'')+'</span></li>').join('')+'</ol><small class="muted">Sentidos y accesos según el extracto OpenStreetMap. Sin tráfico ni cierres en vivo.</small></details>':'')+(t?.routeError?'<p class="form-error">'+E(t.routeError)+'</p>':'')+'</section>';
  };
})(window.LlajtaVoy);
