(function (L) {
  const B = L.ui.button, E = L.escape;
  const components = {
    Presentation: ['Presenta vistas de actores sobre una fuente de verdad. El selector permite cambiar de contexto local sin login.',['Cliente','Restaurante','Repartidor','Administrador','Proveedor de pagos'],[],[]],
    ApiGateway: ['Resuelve rutas, valida el actor y su recurso, aplica 60 solicitudes por minuto y registra latencia y resultado. La ráfaga usa una cuota aislada y la recuperación permanece accesible.', ['GET /api/restaurants','POST /api/orders','PATCH /api/orders/:id/status','GET /api/tracking/:id'],[],[]],
    CatalogService: ['Consulta restaurantes y administra productos del establecimiento seleccionado.',['GET /api/restaurants/:id/menu','PATCH /api/products/:id','POST /api/products'],[],[]],
    RestaurantService: ['Recibe pedidos aprobados y controla aceptación, rechazo y preparación.',['PATCH /api/orders/:id/status'],['order.accepted','order.rejected','order.preparing','order.ready'],['order.created']],
    OrderService: ['Valida carrito, precios y transiciones. Mantiene el pedido único y su historial.',['POST /api/orders','GET /api/orders/:id','PATCH /api/orders/:id/status'],['order.created','order.cancelled','delivery.*'],[]],
    PaymentService: ['Procesa efectivo, QR y tarjeta con un proveedor local. Registra aprobación, rechazo y reversión sin dinero ni datos bancarios reales.',['POST /api/payments','GET /api/payments','GET /api/payments/:id','GET /api/orders/:id/receipt'],['payment.processing','payment.approved','payment.rejected','payment.refunded'],['payment.*']],
    DispatchService: ['Encuentra al repartidor disponible más cercano; si rechaza, ofrece al siguiente.',['Consumidor de q.dispatch.orders'],['driver.search.started','driver.offer.created'],['order.ready']],
    DriverService: ['Gestiona disponibilidad, ofertas y asignación sin exponer pedidos de otros repartidores.',['PATCH /api/drivers/:id','POST /api/offers/:id/accept','POST /api/offers/:id/reject'],['driver.offer.accepted','driver.offer.rejected','driver.assigned'],['driver.offer.created']],
    TrackingService: ['Interpola rutas en requestAnimationFrame. Guarda y publica cada 750 ms. Retoma el punto persistido al recargar. Seguimiento de cámara automático cada 250 ms, rastro vial y telemetría explícitamente simulada.',['GET /api/tracking/:id','POST /api/tracking/:id','PATCH /api/tracking/:id'],['tracking.position.updated','delivery.arriving'],[]],
    NotificationService: ['Crea mensajes idempotentes, reintenta fallos y conserva el estado de lectura.',['Centro de notificaciones del cliente'],['notification.created','notification.sent','notification.failed'],['order.*','driver.assigned','delivery.*']],
    AnalyticsService: ['Consume los eventos una sola vez y deriva indicadores del estado operativo real.',['Panel de Operaciones'],[],['#']],
    EventBroker: ['Distribuye mensajes por routing key. Registra ACK/NACK, hasta tres intentos con espera creciente y Dead Letter Queue.',['publish','subscribe','reprocess'],['delivery.events'],['Eventos registrados']],
    Queues: ['Entrega independiente por consumidor. La DLQ permite inspeccionar error y reprocesar el mensaje.',['q.restaurant.orders','q.dispatch.orders','q.driver.offers','q.notifications','q.analytics','q.audit','q.payments'],[],['Bindings de topic exchange']],
    DatabaseService: ['Encapsula localStorage y serializa catálogo, pedidos, pagos, mensajes, eventos y notificaciones. Si falla, conserva la sesión en memoria.',['getOrders','saveOrder','updateOrder','getEvents','getDrivers','reset'],[],[]]
  };
  L.views.arquitectura = { title:'Arquitectura', subtitle:'Administrador · Responsabilidades, eventos y límites.', selected:'ApiGateway',
    render() { const c = components[this.selected]; const layer = (label,names) => '<div class="architecture-layer"><span class="eyebrow">'+label+'</span><div class="architecture-nodes">'+names.map(name => B('architecture-component',name,{name},null,this.selected===name?'selected':'')).join('')+'</div></div>'; return '<div class="architecture-layout"><section class="panel architecture-diagram">'+layer('PRESENTATION',['Presentation'])+'<div class="flow-line"></div>'+layer('API GATEWAY',['ApiGateway'])+'<div class="flow-line"></div>'+layer('SERVICES',['CatalogService','RestaurantService','OrderService','PaymentService','DispatchService','DriverService','TrackingService','NotificationService','AnalyticsService'])+'<div class="flow-line"></div>'+layer('EVENT BROKER',['EventBroker'])+'<div class="flow-line"></div>'+layer('QUEUES',['Queues'])+'<div class="flow-line"></div>'+layer('DATA STORAGE',['DatabaseService'])+'</section><aside class="panel component-details"><span class="eyebrow">COMPONENTE SELECCIONADO</span><h2>'+this.selected+'</h2><h4>Responsabilidad</h4><p>'+E(c[0])+'</p>'+[['Endpoints / operaciones',c[1]],['Eventos producidos',c[2]],['Eventos consumidos',c[3]]].map(([title,items]) => '<h4>'+title+'</h4><ul>'+ (items.length?items.map(i => '<li><code>'+E(i)+'</code></li>').join(''):'<li>Sin eventos directos</li>')+'</ul>').join('')+'</aside></div><section class="panel"><h3>Actores y límites de acceso</h3><div class="table-wrap"><table><thead><tr><th>Actor</th><th>Responsabilidades</th><th>Límite de acceso</th></tr></thead><tbody>'+[['Cliente','Consultar catálogo, pedir, pagar y seguir su entrega.','Sus pedidos, direcciones y comprobantes.'],['Restaurante','Administrar su menú, aceptar, rechazar y preparar pedidos.','Su establecimiento y pedidos asignados.'],['Repartidor','Declarar disponibilidad, aceptar entregas y enviar ubicación.','Entregas asignadas; ubicación durante entrega activa.'],['Administrador','Gestionar altas, incidentes y auditoría operativa.','Operaciones, Middleware y Arquitectura; acciones auditadas.'],['Proveedor de pagos','Procesar transacciones y notificar su estado.','Intercambio validado con PaymentService.']].map(row => '<tr>'+row.map(cell => '<td>'+cell+'</td>').join('')+'</tr>').join('')+'</tbody></table></div><p class="muted">Los servicios están separados por responsabilidad y coordinados por eventos dentro de un único navegador. Los controles de actor son locales; una integración real requiere autenticación y autorización de servidor.</p></section>'; },mount() { document.querySelectorAll('[data-action=architecture-component]').forEach(button => button.setAttribute('aria-pressed', button.dataset.name===this.selected ? 'true' : 'false')); } };
})(window.LlajtaVoy);
