(function(L){
  'use strict';const DB=L.core.DatabaseService,B=L.ui.button,E=L.escape;
  const V=L.views.operaciones={
    title:'Administración',subtitle:'El equipo, los pedidos y la atención del servicio.',tab:'Resumen',selectedOrder:null,
    render(){const tabs=[['Resumen','monitoring'],['Pedidos','receipt_long'],['Restaurantes','restaurant'],['Repartidores','two_wheeler'],['Incidentes','warning'],['Pagos','payments']];
      return '<nav class="tabs admin-tabs" aria-label="Administración">'+tabs.map(([tab,icon])=>B('admin-tab',tab,{tab},icon,this.tab===tab?'active':'')).join('')+'</nav>'+({Resumen:()=>this.summary(),Pedidos:()=>this.orders(),Restaurantes:()=>this.restaurants(),Repartidores:()=>this.drivers(),Incidentes:()=>this.incidents(),Pagos:()=>L.views.pagos.render()})[this.tab]();},
    summary(){const s=L.services.AnalyticsService.summary();return L.ui.kpis([['Pedidos de hoy',s.today,'receipt_long'],['Entregas activas',s.active,'two_wheeler'],['En preparación',s.preparing,'restaurant'],['Buscando repartidor',s.searching,'search'],['Entregados',s.delivered,'check_circle'],['Repartidores libres',s.available,'person'],['Ventas aprobadas',L.money(s.sales),'payments'],['Entrega promedio',s.average==null?'Sin entregas':s.average.toFixed(1)+' min','schedule']])+this.follow()+'<div class="two-columns"><section class="panel"><div class="section-head"><h3>Territorio y flota</h3><span class="badge">Seguimiento simulado</span></div><div id="operations-map" class="map"></div><p class="muted">Azul: ruta activa · Verde: recorrido realizado · Discontinua: recorrido previsto. Toca un punto para ver el destino, seguir la entrega o contactar al equipo.</p></section><section class="panel"><h3>Pedidos por hora</h3><div id="hour-chart" class="chart"></div><h3>Estado de los pedidos</h3><div id="state-chart" class="chart"></div></section></div>'+this.activity();},
    orders(){const rows=DB.getOrders().slice().reverse();return this.follow()+'<section class="panel"><div class="section-head"><h3>Pedidos y entregas</h3><span>'+rows.length+' pedidos</span></div><div class="table-wrap"><table><thead><tr><th>Pedido</th><th>Cliente</th><th>Restaurante</th><th>Repartidor</th><th>Estado</th><th>Total</th><th>Llegada estimada</th><th>Opciones</th></tr></thead><tbody>'+rows.map(o=>'<tr><td>'+E(o.id)+'</td><td>'+E(o.customerName)+'</td><td>'+E(o.restaurantName)+'</td><td>'+E(o.driverId?L.services.DriverService.get(o.driverId).name:'Por asignar')+'</td><td>'+L.ui.badge(o.status)+'</td><td>'+L.money(o.total)+'</td><td data-track="'+E(o.id)+'" data-metric="eta">'+(L.core.StateMachine.terminal.includes(o.status)?'Finalizado':o.tracking?o.tracking.eta+' min':'Por confirmar')+'</td><td>'+B('inspect-order','Ver pedido',{id:o.id},'receipt_long')+B('watch-order','Seguir entrega',{id:o.id},'route')+'</td></tr>').join('')+'</tbody></table></div>'+(rows.length?'':L.ui.empty('Aún no hay pedidos','Las compras y sus entregas aparecerán aquí.'))+'</section>';},
    restaurants(){return '<section class="panel"><div class="section-head"><h3>Restaurantes del servicio</h3>'+B('new-restaurant','Agregar restaurante',{},'add','primary')+'</div><div class="management-grid">'+DB.getRestaurants().map(r=>'<article class="management-card"><div class="section-head"><h3>'+E(r.name)+'</h3>'+L.ui.badge(r.open?'Abierto':'Cerrado')+'</div><p>'+E(r.address)+'</p><small>'+E(r.category)+' · '+E(r.zone)+'</small><div class="actions">'+B('restaurant-open',r.open?'Cerrar temporalmente':'Abrir establecimiento',{id:r.id,open:!r.open},'restaurant')+B('contact-role','Contactar',{actor:'restaurant',recipient:r.id},'notifications')+'</div></article>').join('')+'</div></section>';},
    drivers(){return '<section class="panel"><div class="section-head"><h3>Equipo de reparto</h3>'+B('new-driver','Agregar repartidor',{},'add','primary')+'</div><div class="management-grid">'+DB.getDrivers().map(d=>'<article class="management-card"><div class="section-head"><h3>'+E(d.name)+'</h3>'+L.ui.badge(d.status)+'</div><p>'+E(d.vehicle)+'</p><small>'+(d.orderId?'Pedido asignado: '+E(d.orderId):'Sin pedido asignado')+' · '+d.deliveries+' entregas completadas</small><div class="actions">'+(d.orderId?'<span class="badge">Entrega en curso</span>':B('driver-availability',d.status==='OFFLINE'?'Habilitar disponibilidad':'Pausar disponibilidad',{id:d.id,available:d.status==='OFFLINE'},'person'))+B('contact-role','Contactar',{actor:'driver',recipient:d.id,orderId:d.orderId || ''},'notifications')+'</div></article>').join('')+'</div></section>';},
    incidents(){const rows=DB.getEvents().filter(e=>e.routingKey==='system.probe' && e.payload.incident).slice().reverse();return '<section class="panel"><div class="section-head"><h3>Atención de incidentes</h3>'+B('incident','Registrar incidente',{},'warning','primary')+'</div>'+(rows.map(e=>'<article class="incident-card"><div class="section-head"><strong>'+E(e.payload.orderId || 'Aviso general')+'</strong><small>'+L.time(e.timestamp)+'</small></div><p>'+E(e.payload.incident)+'</p></article>').join('') || L.ui.empty('Sin incidentes registrados','Los avisos del servicio aparecerán aquí.'))+'</section>'+this.activity()+'<section class="panel"><h3>Respaldo de la operación</h3><p class="muted">Descarga una copia de los datos guardados en este navegador.</p>'+'<div class="actions">'+B('export','Descargar respaldo',{},'download')+B('reset','Reiniciar demostración',{},'refresh')+'</div>'+'</section>';},
    activity(){const texts=[['/api/admin/restaurants','Restaurante incorporado'],['/api/admin/drivers','Repartidor incorporado'],['/api/admin/incident','Incidente registrado'],['/api/restaurants/','Apertura de restaurante actualizada'],['/api/products/','Producto actualizado'],['/api/products','Producto incorporado'],['/api/drivers/','Disponibilidad actualizada'],['/api/messages','Mensaje gestionado'],['/api/orders/','Estado del pedido actualizado'],['/api/orders','Pedido creado']],rows=DB.state.requests.filter(r=>r.method!=='GET' && texts.some(([p])=>r.endpoint.startsWith(p))).slice(-12).reverse();return '<section class="panel"><h3>Actividad del servicio</h3>'+(rows.map(r=>'<div class="list-row"><strong>'+texts.find(([p])=>r.endpoint.startsWith(p))[1]+'</strong><small>'+L.time(r.timestamp)+'</small><span>'+ (r.status>=200 && r.status<300?'Completado':'No completado')+'</span></div>').join('') || '<p class="muted">Las acciones del equipo aparecerán aquí.</p>')+'</section>';},
    follow(){const o=DB.getOrders().find(o=>o.id===this.selectedOrder);return o?'<section class="panel compact"><h3>Entrega '+E(o.id)+'</h3><p class="muted">Supervisa el recorrido y contacta al repartidor.</p></section>'+L.ui.tracking(o):'';},
    mount(){if(['Resumen','Pedidos'].includes(this.tab)){const o=DB.getOrders().find(o=>o.id===this.selectedOrder);if(o)L.maps.MapManager.mount('tracking-map',L.maps.MapManager.order(o));}if(this.tab!=='Resumen')return;L.maps.MapManager.mount('operations-map',L.maps.MapManager.overview({fleet:true}));const orders=DB.getOrders(),hours=[...new Set(orders.map(o=>new Date(o.createdAt).getHours()))].sort((a,b)=>a-b),states=[...new Set(orders.map(o=>o.status))];L.ui.charts.render('hour-chart',hours.length?hours.map(h=>h+':00'):['Sin pedidos'],hours.length?hours.map(h=>orders.filter(o=>new Date(o.createdAt).getHours()===h).length):[0]);L.ui.charts.render('state-chart',states.length?states.map(L.core.StateMachine.label):['Sin pedidos'],states.length?states.map(s=>orders.filter(o=>o.status===s).length):[0]);}
  };
})(window.LlajtaVoy);
