(function(L){
  'use strict';const DB=L.core.DatabaseService,E=L.escape,B=L.ui.button;
  const labels={PROCESSING:'Procesando',APPROVED:'Aprobados',REJECTED:'Rechazados',REFUNDED:'Reembolsados'};
  L.views.pagos={title:'Proveedor de pagos',subtitle:'Transacciones locales y notificaciones de estado.',filter:'ALL',
    render(){const all=L.services.PaymentService.list({actor:'payment-provider',providerId:'local-payment-provider'}),rows=all.filter(p=>this.filter==='ALL' || p.status===this.filter);
      return L.ui.kpis([['Aprobados',all.filter(p=>p.status==='APPROVED').length,'check_circle'],['Rechazados',all.filter(p=>p.status==='REJECTED').length,'close'],['Reembolsados',all.filter(p=>p.status==='REFUNDED').length,'refresh'],['Importe aprobado',L.money(all.filter(p=>p.status==='APPROVED').reduce((n,p)=>n+p.amount,0)),'payments']])+'<section class="panel"><h3>Transacciones del proveedor local</h3><p class="muted">Al crear un pedido, el sistema procesa el pago una sola vez y notifica su resultado. La cancelación correspondiente actualiza el reembolso. No se realizan cobros reales.</p><nav class="tabs" aria-label="Estado del pago">'+[['ALL','Todos'],...Object.entries(labels)].map(([status,title])=>B('payment-filter',title,{status},null,this.filter===status?'active':'')).join('')+'</nav><div class="table-wrap payment-list"><table><thead><tr><th>Transacción</th><th>Pedido</th><th>Importe</th><th>Método</th><th>Estado</th><th>Hora</th><th>Acción</th></tr></thead><tbody>'+rows.slice().reverse().map(p=>'<tr><td>'+E(p.id)+'</td><td>'+E(p.orderId)+'</td><td>'+L.money(p.amount)+'</td><td>'+E(p.method)+'</td><td>'+L.ui.badge(p.status)+'</td><td>'+L.time(p.timestamp)+'</td><td>'+B('payment-detail','Referencia',{id:p.id},'receipt_long')+'</td></tr>').join('')+'</tbody></table></div>'+(rows.length?'':L.ui.empty('Sin transacciones en este estado','Crea un pedido desde Cliente para observar el procesamiento automático.'))+'</section><section class="panel"><h3>Notificaciones recibidas</h3><p class="muted">Confirmaciones consumidas por el servicio de pagos; los eventos completos se auditan en Middleware.</p>'+DB.state.paymentReceipts.filter(r=>all.some(p=>p.id===r.paymentId)).slice(-15).reverse().map(r=>'<div class="list-row"><strong>'+E(r.status)+'</strong><span>'+E(r.paymentId)+'</span><small>'+L.time(r.timestamp)+'</small></div>').join('')+'</section>';},
    mount(){}
  };
})(window.LlajtaVoy);
