(function (L) {
  const DB = L.core.DatabaseService, B = L.ui.button, E = L.escape;
  L.views.repartidor = { title:'Repartidor', subtitle:'Cada entrega conecta una historia.', id:'d1',
    render() { const d = L.services.DriverService.get(this.id), o = d.orderId ? DB.getOrder(d.orderId) : null; const history = DB.getOrders().filter(o => o.driverId===d.id && o.status==='DELIVERED'); let content = '';
      if (o && d.status==='OFFERED') { const r = L.services.CatalogService.restaurant(o.restaurantId), distance = L.maps.Routes.length(L.maps.Routes.create([d.lat,d.lng],[r.lat,r.lng]))+L.maps.Routes.length(L.maps.Routes.create([r.lat,r.lng],[o.lat,o.lng])); content = '<section class="offer panel"><span class="eyebrow">NUEVA ENTREGA</span><h2>'+E(o.restaurantName)+'</h2><p>'+E(r.address)+' → '+E(o.address)+'</p>'+L.ui.kpis([['Recorrido estimado',distance.toFixed(2)+' km','route'],['Tiempo estimado',Math.ceil(distance/.3)+' min','schedule'],['Ganancia',L.money(o.delivery),'payments']])+'<div class="actions">'+B('accept-offer','Aceptar entrega',{id:o.id},'check_circle','primary')+B('reject-offer','Rechazar oferta',{id:o.id},'close')+'</div></section>'; }
      else if (o) { let actions = ''; if (o.status==='DRIVER_ASSIGNED') actions = o.tracking?.arrived ? B('order-status','Pedido recogido',{id:o.id,status:'PICKED_UP'},'check_circle','primary') : B('start-route',o.tracking?.running?'Ruta al restaurante en marcha':'Iniciar ruta al restaurante',{id:o.id,leg:'restaurant'},'route','primary'); if (['PICKED_UP','ON_ROUTE','ARRIVING'].includes(o.status)) actions = o.tracking?.leg==='customer' && o.tracking.arrived ? B('order-status','Confirmar entrega',{id:o.id,status:'DELIVERED'},'check_circle','primary') : B('start-route',o.tracking?.running && o.tracking.leg==='customer'?'Ruta al cliente en marcha':'Iniciar ruta al cliente',{id:o.id,leg:'customer'},'route','primary'); if (o.tracking?.running) actions += B('pause-route','Pausar ruta',{id:o.id},'schedule'); if (['DRIVER_ASSIGNED','PICKED_UP','ON_ROUTE','ARRIVING'].includes(o.status)) actions += B('fail-delivery','Reportar entrega fallida',{id:o.id},'warning'); content = '<div class="two-columns">'+L.ui.tracking(o)+L.ui.orderCard(o,actions)+'</div>'; }
      else content = L.ui.empty(d.status==='OFFLINE'?'Estás desconectado':'Listo para la siguiente entrega',d.status==='OFFLINE'?'Activa tu disponibilidad para recibir ofertas.':'Recibirás una oferta cuando un restaurante tenga un pedido listo.');
      return '<div class="section-head"><div class="driver-heading"><div class="avatar">'+E(d.name[0])+'</div><div><h2>'+E(d.name)+'</h2><p class="muted">'+E(d.vehicle)+' · '+(d.rating || 'Sin calificar')+'</p></div></div><label>Repartidor<select id="driver-selector">'+DB.getDrivers().map(x => '<option value="'+x.id+'" '+(d.id===x.id?'selected':'')+'>'+E(x.name)+(x.status==='OFFERED'?' · Nueva oferta':'')+'</option>').join('')+'</select></label></div><div class="availability"><div>'+L.ui.badge(d.status)+'<span> Disponible para entregas</span></div><button data-action="driver-availability" data-available="'+(d.status==='OFFLINE')+'" '+(d.orderId?'disabled':'')+'>'+(d.status==='OFFLINE'?'Conectarme':'Desconectarme')+'</button></div>'+L.ui.kpis([['Entregas completadas',d.deliveries,'check_circle'],['Ganancias',L.money(history.reduce((s,o) => s+o.delivery,0)),'payments'],['Asignación actual',o?o.id:'Sin asignación','receipt_long']])+content+'<section class="panel compact"><h3>Historial de entregas</h3>'+(history.map(o => '<div class="list-row"><strong>'+o.id+'</strong><span>'+E(o.restaurantName)+'</span><span>'+L.money(o.delivery)+'</span>'+L.ui.badge(o.status)+'</div>').join('') || '<p class="muted">Tus entregas completadas aparecerán aquí.</p>')+'</section>'; },
    mount() { const d = L.services.DriverService.get(this.id); if (d.orderId && d.status!=='OFFERED') { const o = DB.getOrder(d.orderId); L.maps.MapManager.mount('tracking-map',L.maps.MapManager.order(o)); const buttons = document.querySelectorAll('[data-action=start-route]'); if (o.tracking?.running) buttons.forEach(b => { b.disabled = true; }); } }
  };
})(window.LlajtaVoy);
